### PR TITLE
Merge release

### PR DESCRIPTION
**Pull request by mattip**
This is needed to convince `git describe --tags --abbrev=8` to add the 0.3.10 tag. Before this PR HEAD on `develop` reported
`v0.3.9-849-gdf706670`, after this merge it reports `v0.3.10-493-g0eda7ac2`. 

Merging the release back into the develop branch would be helpful after each release for downstream packagers [like numpy](https://anaconda.org/multibuild-wheels-staging/openblas-libs/files): note the file name is `openblas-v0.3.9-452-g349b722d` even though it is built off a commit *after* the 0.3.10 release.

### CODE REVIEW

**Comment by martin-frbg** [comment]
I am not entirely convinced this would work without messing up the develop branch shortly before 0.3.11 :(

**Comment by mattip** [comment]
Sorry, feel free to close it then, or maybe leave it open as a reminder to merge the release branch back to develop shortly after the release?

**Comment by martin-frbg** [comment]
Most likely that is just another git feature that I am not really familiar with... but I see we have been there before (#645) with some arguing that only the hash itself should be considered significant when building from `develop`

**Comment by mattip** [comment]
In that issue there is this comment, which is an opinion I only partially agree with
>  Yes you are right, this bug should be closed. In v0.2.9.rc1-679-ga96a4cb only a96a4cb is meaningful, that's how git and git describes works.

That may be how `git describe` works, but it is not how your users expect `git describe --tags` to work. After a release, I would expect the active branch to continue after the tag. Is it is a big ask to merge the release branch back into develop for the convenience of downstream packagers after the release is tagged? This PR changes no actual files, it only changes the appearance of tags on branches.

**Comment by martin-frbg** [comment]
I'm ok with merging back after the release, and I would merge your PR if I had a clear idea how the history of the `develop` branch would look after its application (i.e. what hash would get tagged as 0.3.10 retroactively, and if `git log` would still show the expected sequence of commits). With 0.3.9 I am pretty sure the mergeback of the tag must have happened as a side effect of a trivial merge conflict resolution - differing version strings in the (c)makefiles or something like that)

**Comment by mattip** [comment]
cool thanks. I will close this and try to remember to make sure it is done after the upcoming release. I hope it goes smoothly.

**Pull request closed without merging**
