### PR TITLE
Address unlikely memleak in zimatcopy interface

### PR DESCRIPTION
**Pull request by brada4**
Temp buffer is leaked in (unlikely) fall-through path, now no more.

### CODE REVIEW

**Comment by martin-frbg** [comment]
What is the motivation for this change, which seems to boil down to the addition of a single "free(b)" for the impossible case that "order" or "trans" have an illegal value ? At least I would like to see all the early returns preserved, if only for human readability.

**Comment by brada4** [comment]
Interface can be called by user directly, 
Correct would be to malloc b before it is used, i.e in 2 valid places, and freed in branches. I am not sure about preserving readability then.

**Comment by brada4** [comment]
ie if trans=grabage, then leak as it stands now.

**Comment by martin-frbg** [comment]
Still would prefer to see just the minimal change made (i.e. addition of the "free(b)" before the return of the fall-through path, no removal of the early returns)

**Comment by brada4** [comment]
Can fix that. no probl

**Pull request merged**
