### PR TITLE
Fix compilation and linking of the ctests on Windows/LLVM19

### PR DESCRIPTION
**Pull request by martin-frbg**
as implemented by h-vetinari in the LAPACK feedstock for conda-forge

### CODE REVIEW

**Comment by isuruf** [comment]
This is wrong behaviour for windows. We need to use `__declspec(dllexport)` and `__declspec(dllimport)` machinery.

**Comment by martin-frbg** [comment]
thanks - I had missed that there was a followup in https://github.com/conda-forge/lapack-feedstock/pull/76/files after h-vetinari pointed me to the original patch.
Guess these should ideally be upstreamed to Reference-LAPACK as well...

**Comment by isuruf** [comment]
yes, I'll send a PR upstream

**Comment by martin-frbg** [comment]
On giving this a second look, the entire (original) patch should be relevant to the implementation of tests and xerbla in the Reference version of CBLAS only, so this PR is entirely spurious. (The OpenBLAS implementation uses neither the bytewise rewriting of Fortran character variables to C strings nor the deferred adjustment of error codes in the row major cases that the two global variables in the reference CBLAS are for)

**Pull request closed without merging**
