### PR TITLE
Address redundant code concern #2113

### PR DESCRIPTION
**Pull request by brada4**
Remove extra unchecked checking step three times from getrf_parallel.c

### CODE REVIEW

**Comment by brada4** [comment]
Trigger new CI

**Comment by martin-frbg** [comment]
new CI had a dummy recipe only, abusing this PR to try an actual build now :slightly_smiling_face:

**Comment by tylerjereddy** [comment]
I usually set up pipelines on my fork of a repo and debug there rather than pushing to develop, then open a PR when it is ready. I guess that has more upfront time cost though.

**Comment by tylerjereddy** [comment]
I think you're making changes through the Azure web interface and then those are actually getting committed to develop--maybe you know that, but just checking. It can make the commit history a bit messy vs. adjusting the config yml in a PR.

**Comment by martin-frbg** [comment]
> I think you're making changes through the Azure web interface and then those are actually getting committed to develop--maybe you know that, but just checking. It can make the commit history a bit messy vs. adjusting the config yml in a PR.

Err, actually I was doing direct commits to develop as I did not expect it to get so messy. Sorry.

**Pull request merged**
