### PR TITLE
possible cgemv,caxpy,cdot fix

### PR DESCRIPTION
**Pull request by quickwritereader**
align buffers and also use vec_vsx_ld vec_vsx_st pairs to hint gcc to use new load/store instructions

### CODE REVIEW

**Comment by quickwritereader** [comment]
#2233 
Well, it turned out that gcc already provides vector intrinsics for (unaligned or word aligned) load store instructions. I re-wrote explicitly to avoid undesired GCC-8 instruction choice.

**Comment by martin-frbg** [comment]
Unfortunately I am still getting errors from CGEMV, CHEMV and CTRMV with this patch.

**Comment by martin-frbg** [comment]
Seems to be a genuine coding error, as disabling optimization no longer helps - with the pragma added back, computed results for CGEMV actually turn to all zero.

**Comment by martin-frbg** [comment]
Thanks, that fixes it for me so the travis error is probably unrelated. (I have restarted that CI job now)

**Comment by martin-frbg** [comment]
beginning to suspect that there might be something in this PR that the old gcc5 cannot cope with...
unfortunately I cannot create an Ubuntu16 instance in the minicloud at the moment, will try again later.

**Comment by quickwritereader** [comment]
thanks @martin-frbg. 
lets keep it open. I will check it again next week.

**Comment by martin-frbg** [comment]
Build passes on Power8/Ubuntu 16.04/gcc 5.4.0 (same configuration as the "failed" Travis job) in the unicamp.br minicloud,

**Comment by martin-frbg** [comment]
Err, after removing the QUIET_MAKE  from .travis.yml in a private build it looks likely that our travis "ppc64le" job is actually building for x86_64 (in the DYNAMIC_ARCH part at least) before it runs out of time. I wonder if that is a new development and/or a side effect of the "unannounced beta" status of that configuration.

**Comment by isuruf** [comment]
@martin-frbg, builds on `travis-ci.com` don't have ppc64le builds. `travis-ci.org` does though. Did you try `travis-ci.org` or `travis-ci.com`?

**Comment by martin-frbg** [comment]
Not sure which of the two xianyi set up, but I strongly suspect it is the .org - and this setup worked for months until it suddenly failed two days ago, just as we tried to debug #2237. I have commented out this part of the travis configuration file for now after confirming that both single-target and dynamic arch builds actually do work fine after quickwritereader's patch.

**Comment by isuruf** [comment]
xianyi's is in travis-ci.org (https://travis-ci.org/xianyi/openblas) which is the correct domain.

**Comment by martin-frbg** [comment]
You are right that I may have had inadvertently linked my fork to travis-ci.com (I had removed and re-forked it recently, and somehow my account has OpenBLAS linked to both .com and .org), Just now the ppc build seems to be working again - not sure what the original issue was exactly due to the QUIET_MAKE setting, perhaps some glitch at travis had temporarily moved everything to the .com domain

**Pull request merged**
