### PR TITLE
Prevent powershell from adding a BOM to test input

### LINKED ISSUE #3594: CTest failure with windows build
Hello, i built OpenBLAS on Windows 10 with clang/flang as shown [here](https://github.com/xianyi/OpenBLAS/wiki/How-to-use-OpenBLAS-in-Microsoft-Visual-Studio#1-native-msvc-abi)
The build itself was successful but running ctest resulted in some errors possibly with the script test\test_helper.ps1. 

OpenBLAS was build with:
<pre><code>
cmake .. -G "Ninja"  -DCMAKE_C_COMPILER=clang-cl -DCMAKE_Fortran_COMPILER=flang -DCMAKE_MT=mt -DBUILD_WITHOUT_LAPACK=no -DNOFORTRAN=0 -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=ON
</pre></code>

I run ctest in windows powershell and powershell 7 but both resulted in:
<pre><code>
ctest --config Release --rerun-failed --output-on-failure
Test project C:/Users/George/source/libraries/openblas/build_rel
      Start  2: sblas1
 1/16 Test  #2: sblas1 ...........................Exit code 0xc0000135
***Exception:   0.10 sec

      Start  3: sblas2
 2/16 Test  #3: sblas2 ...........................***Failed    0.31 sec
& : The term 'file' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the
name, or if a path was included, verify that the path is correct and try again.
At C:\Users\George\source\libraries\openblas\build_rel\test\test_helper.ps1:3 char:31
+ If ((Get-Content $args[1] | & file - | %{$_ -match "BOM"}) -contains  ...
+                               ~~~~
    + CategoryInfo          : ObjectNotFound: (file:String) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : CommandNotFoundException

      Start  4: sblas3
 3/16 Test  #4: sblas3 ...........................***Failed    0.31 sec
& : The term 'file' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the
name, or if a path was included, verify that the path is correct and try again.
At C:\Users\George\source\libraries\openblas\build_rel\test\test_helper.ps1:3 char:31
+ If ((Get-Content $args[1] | & file - | %{$_ -match "BOM"}) -contains  ...
+                               ~~~~
    + CategoryInfo          : ObjectNotFound: (file:String) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : CommandNotFoundException

      Start  5: dblas1
 4/16 Test  #5: dblas1 ...........................Exit code 0xc0000135
***Exception:   0.01 sec

      Start  6: dblas2
 5/16 Test  #6: dblas2 ...........................***Failed    0.31 sec
& : The term 'file' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the
name, or if a path was included, verify that the path is correct and try again.
At C:\Users\George\source\libraries\openblas\build_rel\test\test_helper.ps1:3 char:31
+ If ((Get-Content $args[1] | & file - | %{$_ -match "BOM"}) -contains  ...
+                               ~~~~
    + CategoryInfo          : ObjectNotFound: (file:String) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : CommandNotFoundException

      Start  7: dblas3
 6/16 Test  #7: dblas3 ...........................***Failed    0.31 sec
& : The term 'file' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the
name, or if a path was included, verify that the path is correct and try again.
At C:\Users\George\source\libraries\openblas\build_rel\test\test_helper.ps1:3 char:31
+ If ((Get-Content $args[1] | & file - | %{$_ -match "BOM"}) -contains  ...
+                               ~~~~
    + CategoryInfo          : ObjectNotFound: (file:String) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : CommandNotFoundException

      Start  8: cblas1
 7/16 Test  #8: cblas1 ...........................Exit code 0xc0000135
***Exception:   0.01 sec

      Start  9: cblas2
 8/16 Test  #9: cblas2 ...........................***Failed    0.31 sec
& : The term 'file' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the
name, or if a path was included, verify that the path is correct and try again.
At C:\Users\George\source\libraries\openblas\build_rel\test\test_helper.ps1:3 char:31
+ If ((Get-Content $args[1] | & file - | %{$_ -match "BOM"}) -contains  ...
+                               ~~~~
    + CategoryInfo          : ObjectNotFound: (file:String) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : CommandNotFoundException

      Start 10: cblas3
 9/16 Test #10: cblas3 ...........................***Failed    0.32 sec
& : The term 'file' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the
name, or if a path was included, verify that the path is correct and try again.
At C:\Users\George\source\libraries\openblas\build_rel\test\test_helper.ps1:3 char:31
+ If ((Get-Content $args[1] | & file - | %{$_ -match "BOM"}) -contains  ...
+                               ~~~~
    + CategoryInfo          : ObjectNotFound: (file:String) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : CommandNotFoundException

      Start 11: zblas1
10/16 Test #11: zblas1 ...........................Exit code 0xc0000135
***Exception:   0.01 sec

      Start 12: zblas2
11/16 Test #12: zblas2 ...........................***Failed    0.32 sec
& : The term 'file' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the
name, or if a path was included, verify that the path is correct and try again.
At C:\Users\George\source\libraries\openblas\build_rel\test\test_helper.ps1:3 char:31
+ If ((Get-Content $args[1] | & file - | %{$_ -match "BOM"}) -contains  ...
+                               ~~~~
    + CategoryInfo          : ObjectNotFound: (file:String) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : CommandNotFoundException

      Start 13: zblas3
12/16 Test #13: zblas3 ...........................***Failed    0.31 sec
& : The term 'file' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the
name, or if a path was included, verify that the path is correct and try again.
At C:\Users\George\source\libraries\openblas\build_rel\test\test_helper.ps1:3 char:31
+ If ((Get-Content $args[1] | & file - | %{$_ -match "BOM"}) -contains  ...
+                               ~~~~
    + CategoryInfo          : ObjectNotFound: (file:String) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : CommandNotFoundException

      Start 14: xscblat1
13/16 Test #14: xscblat1 .........................Exit code 0xc0000135
***Exception:   0.01 sec

      Start 17: xdcblat1
14/16 Test #17: xdcblat1 .........................Exit code 0xc0000135
***Exception:   0.01 sec

      Start 20: xccblat1
15/16 Test #20: xccblat1 .........................Exit code 0xc0000135
***Exception:   0.01 sec

      Start 23: xzcblat1
16/16 Test #23: xzcblat1 .........................Exit code 0xc0000135
***Exception:   0.01 sec

0% tests passed, 16 tests failed out of 16

Total Test time (real) =   2.69 sec

The following tests FAILED:
          2 - sblas1 (Exit code 0xc0000135
)
          3 - sblas2 (Failed)
          4 - sblas3 (Failed)
          5 - dblas1 (Exit code 0xc0000135
)
          6 - dblas2 (Failed)
          7 - dblas3 (Failed)
          8 - cblas1 (Exit code 0xc0000135
)
          9 - cblas2 (Failed)
         10 - cblas3 (Failed)
         11 - zblas1 (Exit code 0xc0000135
)
         12 - zblas2 (Failed)
         13 - zblas3 (Failed)
         14 - xscblat1 (Exit code 0xc0000135
)
         17 - xdcblat1 (Exit code 0xc0000135
)
         20 - xccblat1 (Exit code 0xc0000135
)
         23 - xzcblat1 (Exit code 0xc0000135
)
Errors while running CTest
</code></pre>

### PR DESCRIPTION
**Pull request by martin-frbg**
fixes #3594 as suggested by mmuetzel

### CODE REVIEW

**Comment by mmuetzel** [comment]
I'm not sure I understand what the actual issue is. But the following PowerShell command should read a file (with or without BOM) and write it without BOM (as long as those files only contain ASCII characters):
```
Get-Content .\test_file.txt -Encoding UTF8 | Set-Content .\test_file_no_BOM.txt -Encoding ASCII
```

**Comment by martin-frbg** [comment]
The problem is that on "some" Windows hosts in Azure, powershell´s Get-Content prepends a BOM to anything it pipes into an __external__ program, and none of the various internet recipes I tried got it to stop doing that. This behaviour breaks some of the BLAS tests where the name of the output file to create is written as the first parameter in the input file for the test. As the (Fortran) test code does not support UTF, it simply adds the character pattern of the BOM to the filename, the test succeeds but the subsequent check does not find the expected file and reports a failure.
What I tried here is also destined to fail, as the BOM is not there (yet) when piping to the built-in replace command, but gets added in the next stage. #3598 has a different approach where I just try to replace the non-portable `file` command with something equally external but always available on Windows.

**Comment by mmuetzel** [comment]
By default on the system I'm testing, the input encoding is set to ibm850. That might be the reason I didn't see this locally.
I *think* I can reproduce this if I set the input encoding of the console to UTF-8 with BOM with this PowerShell command:
```
[Console]::InputEncoding = New-Object Text.UTF8Encoding $true
```

It might be a good idea to unconditionally set the console input encoding to UTF-8 *without* BOM in that .ps1 script. That way the pipes should behave pretty similarly to what they do on modern Linux:
```
[Console]::InputEncoding = New-Object Text.UTF8Encoding $false
```

**Comment by martin-frbg** [comment]
Thank you for the suggestion - it seems this was not among the many variations I tried in #3563.

**Pull request merged**
