### PR TITLE
Remove prototype of unused, unimplemented function

### PR DESCRIPTION
**Pull request by luzpaz**
Found via `codespell -q 3 -L amin,als,ba,dum,mone,nd,nto,orign -S Changelog.txt,./lapack*`

### CODE REVIEW

**Comment by luzpaz** [comment]
Wasn't sure about this one, so I split it off from #2273

**Comment by martin-frbg** [comment]
Should be harmless (basically just a comment as well, the asterisk alone should be good enough for the compiler), but I agree it makes one wonder if the obvious typo has any ill effect.

**Comment by brada4** [comment]
It is an unused prototype, you can delete it as well.

**Comment by brada4** [comment]
Quite cute that you have to add paragraph of parameters to avoid calling library export 'main'

**Review by brada4 — CHANGES_REQUESTED** [review]
Please change your patch into full removal of unused function prototype.

**Comment by martin-frbg** [comment]
There is an entry for a (nonexisting) beta_thread in driver/level3/Makefile as well, maybe worth researching if an early GotoBLAS actually had the implementation (and if so, why it was dropped).
And we could just as well comment it as "unused" or "unimplemented" rather than delete a harmless bit of framework.

**Comment by luzpaz** [comment]
@brada4 aka you want me to remove line 199 ? 
 
https://github.com/xianyi/OpenBLAS/pull/2274/files#diff-5bc29bcf15879fc42166282316b0602dL199

**Comment by brada4** [comment]
Whole beta-thread function.

**Comment by luzpaz** [comment]
Shall I squash it?

**Comment by martin-frbg** [comment]
Thanks, no need to squash it as that can be done with the merge (if I remember to switch the combobox from "merge pull request" to "squash and merge" :slightly_smiling_face: )

**Comment by brada4** [comment]
@luzpaz - good spotting, esp for an unorthodox tool.

**Pull request merged**
