### PR TITLE
Optimize AVX2 SGEMM & STRMM

### PR DESCRIPTION
**Pull request by wjc404**
Replace KERNEL_16x6 with KERNEL_8x12 to slow down reading on packed matrix A(in L3 cache), as mentioned in issue #2210 .  The performance catchs up with MKL2019 after the change.

### CODE REVIEW

**Comment by wjc404** [comment]
1).1-thread SGEMM test with m=n=k=7023, transa=N and transb=T, on i9 9900K at 4.4 GHz, theoretical 140.8 GFLOPS:

old kernel:
Screenshot from 2020-01-06 18-09-02

new kernel:
Screenshot from 2020-01-06 18-09-09


2).4-thread SGEMM test with m=n=k=10000, transa=T and transb=N, on the same CPU at 4.2 GHz, theoretical 538 GFLOPS:

old kernel:
Screenshot from 2020-01-06 18-14-08

new kernel:
Screenshot from 2020-01-06 18-14-12

3).8-thread test with m=n=k=20000, transa=transb=N on the same CPU at 4.1 GHz, theoretical 1050 GFLOPS:

old kernel:
Screenshot from 2020-01-08 11-01-15

new kernel:
Screenshot from 2020-01-08 11-01-25



4).1-thread STRMM test with m=n=6971, side=L, uplo=U, transa=N and diag=N, on the same CPU at 4.4 GHz, theoretical 140.8 GFLOPS:

old kernel:
Screenshot from 2020-01-06 18-21-11

new kernel:
Screenshot from 2020-01-06 18-21-16

**Comment by wjc404** [comment]
1-thread SGEMM test with m=n=k=5999, transa=N and transb=N, on r7 3700x at 3.6 GHz, theoretical 115.2 GFLOPS:

old kernel:
Screenshot from 2020-01-06 18-51-59

new kernel:
Screenshot from 2020-01-06 18-52-06

4-thread test with m=n=k=10000, transa=transb=T, on the same CPU at 3.6 GHz, theoretical 461 GFLOPS:

old kernel:
Screenshot from 2020-01-06 18-53-23

new kernel:
Screenshot from 2020-01-06 18-53-30

**Comment by wjc404** [comment]
The STRMM kernel passed 1-thread reliability test.
Screenshot from 2020-01-06 19-47-19
Screenshot from 2020-01-08 13-18-47


Test code: 
[strmm_compare_test.zip](https://github.com/xianyi/OpenBLAS/files/4025923/strmm_compare_test.zip)

**Comment by wjc404** [comment]
The SGEMM kernel passed 1-thread reliability test. Ready for merging.
Screenshot from 2020-01-08 14-43-05

**Comment by martin-frbg** [comment]
Great, thanks a lot. Still fascinating to see how much performance can be improved by making things slower.

**Pull request merged**
