### PR TITLE
Optimize SGEMM on SKYLAKEX CPUs

### PR DESCRIPTION
**Pull request by wjc404**
The current SGEMM kernel for SKYLAKEX is not efficient enough, with only half of the performance (1-thread) of Intel MKL on a Xeon Platinum CPU. The problem is from the unbalanced reading rates on packed A and B matrices, similar to that in haswell SGEMM kernel (issue #2210). 
    
Luckily on SKYLAKEX the problem can be solved without changing icopy and ocopy routines. The major part of SGEMM kernel is rewritten. After the change, the 1-thread performance of SGEMM reached 93% of MKL.

### CODE REVIEW

**Comment by wjc404** [comment]
waiting for comparative tests of the 2 kernels on other skylakex platforms :)

**Comment by wjc404** [comment]
Screenshot from 2019-11-03 17-07-06
A SGEMM test with all the combinations of 1<=m<=584 && 1<=n<=69 && 1<=k<=399 passed.
[sgemm_test.zip](https://github.com/xianyi/OpenBLAS/files/3801381/sgemm_test.zip)

**Comment by wjc404** [comment]
1-thread SGEMM comparative test with m=n=k=7000 on Intel Xeon Gold 6149:
old SGEMM kernel:
Screenshot from 2019-11-03 17-34-34

new SGEMM kernel:
Screenshot from 2019-11-03 17-34-38

**Comment by wjc404** [comment]
4-thread SGEMM comparative test with m=n=k=8000 on Intel Core i5-1035G1 (fixed at 1GHz, half AVX512 fma throughput, theoretical maximum 128 GFLOPS):

old SGEMM kernel:
Screenshot from 2019-11-03 23-35-33

new SGEMM kernel:
Screenshot from 2019-11-03 23-35-41

**Comment by wjc404** [comment]
Now 99% 1-thread MKL performance, 96-99% 4-thread MKL performance, on an Intel Xeon Platinum CPU.

**Comment by wjc404** [comment]
A SGEMM test with m=n=k=16823, using 4 threads on Intel Xeon Platinum 8269CY CPU:
Screenshot from 2019-11-04 20-14-31

A SGEMM test with m=n=k=9121, using 1 thread on the same CPU:
Screenshot from 2019-11-04 20-19-52

**Comment by martin-frbg** [comment]
Impressive :)
(And that is with the old icopy/ocopy routines probably holding it back a bit)

**Comment by wjc404** [comment]
some optimizations of AVX512 DGEMM code
now 96% 1-thread MKL DGEMM performance on Intel Xeon Platinum 8269CY, 94% of MKL on Xeon Gold 6149.

A reliability test of the optimized DGEMM kernel passed:
Screenshot from 2019-11-05 14-07-25

**Pull request merged**
