### PR TITLE
Optimize gemv for small M, large N only if it can be done in a threadsafe manner

### LINKED ISSUE #1844: OpenBLAS threadsafety issues for downstream libraries (NumPy)
Since OpenBLAS is one of the most commonly used BLAS implementations with NumPy, there are currently two points being discussed within NumPy. One thing is the spawning of too many threads when using multi processing/python threads (although is probably something we need to find a solution for, but pointers are welcome!).

The main issue is the thread safety of OpenBLAS when multiple threads are used. This may not be problematic for many projects explicitly using OpenBLAS, but NumPy is a bit different:
  * NumPy does not actually know which BLAS is being used.
  * Thus, NumPy has no control on the number of threads (the system default is used).

Together this means NumPy will often use multi threaded OpenBLAS. Now if someone uses a numpy function within threads they might get silently incorrect results (https://github.com/numpy/numpy/issues/11046) and this seems true for OpenBLAS versions 0.2.18, 0.2.20, 0.3.0 (probably generally).

The possibility of silently wrong results deeply troubles me. Downstream users of NumPy are unlikely to be aware of such issues, or might not even notice that they are using BLAS at all. The problem is that there seems to be no easy solution.

We could use locking to disable threading, but that probably is incorrect/unnecessary often as well.
I have been talking with @mattip and others at NumPy, and hoped we can start a small discussion here. Maybe there are fixes/workarounds we can implement in NumPy, but maybe we can also provide help/resources to make OpenBLAS thread safe?

### PR DESCRIPTION
**Pull request by martin-frbg**
commit 8e5a108 tried to improve the performance of #532 but introduced a static array in the process, breaking programs like numpy that call into OpenBLAS from several concurrent threads. Supersedes the simple revert from #1852 with the intention to fix #1844 without sacrificing performance where possible.

### CODE REVIEW

**Comment by brada4** [comment]
Looks like includes the observations from mentioned issue.

**Comment by martin-frbg** [comment]
Sorry, I did not get the comment ? (Unfortunately I cannot test this on my hexacore system this weekend, but I had tested the general idea outlined in the comments on #1852 earlier)

**Comment by brada4** [comment]
It looks that it enables gemv optimisation for OMP only. 
Does not fail with Android UserLAnd (sort of debian chroot, atom CPU) in OMP or pthread builds, though I cannot tell if it ever failed before in this combination.
EDIT: it fails in pre=patches pthread version and ubuntu numpy, though multiprocessorness of this "debian" is not always guaranteed, you somehow need to spin many bg apps to make cpus wake from park. Does not seem possible from "app" I'd wait for more reliable tests...

**Comment by martin-frbg** [comment]
The intention is that it enables the optimization only when the static buffer can be made thread safe, that is either under OMP or when the compiler is capable of assigning C11-like TLS.

**Comment by brada4** [comment]
Patches do the trick most likely just that android tablet chroot is not always multiprocessor like a normal computer....

**Comment by martin-frbg** [comment]
Merged after successful local tests

**Comment by mattip** [comment]
Thanks. Since this is a critical bug for NumPy, will it be part of a bugfix release?

**Comment by martin-frbg** [comment]
Guess 0.3.4 is overdue in any case, will see if I can do it next weekend or at least by the end of this month. Need to try to get a decent handle on the equally ugly #1851 as well.

**Pull request merged**
