### PR TITLE
Lock Management Improvements for Memory Allocation Efficiency

### PR DESCRIPTION
**Pull request by goplanid**
This PR improves the thread contention at a particular lock during memory allocation:

1. Reduction of Lock Overhead: It checks memory initialization flag before acquiring the lock, and hence reduces the lock overhead in non-OpenMP scenarios.
2. Performance Improvements:  This change has shown significant performance gains for small datasets, in both Pthreads and single-thread execution.

Additional fixes:
1. memory_initialized is changed to volatile.
2. A memory write barrier has been added to ensure writes to memory_initialized are visible to other threads.

### CODE REVIEW

**Comment by goplanid** [comment]
Hi @martin-frbg, can you review the PR and provide your insights?

**Comment by goplanid** [comment]
Hi @martin-frbg,  Gentle reminder on the review.

**Comment by martin-frbg** [comment]
Right, I haven't forgotten. Generally if you see me commenting on other issues it does not mean I'm deliberately ignoring you - just that I am trying to move things along that do not require my full attention while I am busy elsewhere.

**Comment by goplanid** [comment]
I understand, thank you @martin-frbg.

**Comment by martin-frbg** [comment]
Took me a moment to understand what I was trying to achieve with what must have originally been #1468 :(
Thanks for the fix

**Pull request merged**
