### PR TITLE
Update logic for generating OpenBLASConfig.cmake

### PR DESCRIPTION
**Pull request by 10km**
The `OpenBLASConfig.cmake` gererated by `Makefile.install` sets `OpenBLAS_INCLUDE_DIRS` `OpenBLAS_LIBRARIES` to an absolut path.

For example:
```cmake
SET(OpenBLAS_VERSION "0.2.20.dev")
SET(OpenBLAS_INCLUDE_DIRS D:/openblase.release/include)
SET(OpenBLAS_LIBRARIES D:/openblase.release/bin/libopenblas.dll)
```
In most cases, this is not a problem.

But if the install folder is moved, the `OpenBLAS_INCLUDE_DIRS` and `OpenBLAS_LIBRARIES` will be invalid.

Another problem is:

>If building with MSVC, the value of `OpenBLAS_LIBRARIES`  should not refer to `libopenblas.dll`, but `libopenblas.dll.a` instead.

This Pull Request will fix above two problems. 

In Windows, the `OpenBLASConfig.cmake` will be generated as below:

(`OpenBLAS_LIBRARIES`  refers to a dynamic library. If building with MinGW and  setting `OpenBlas_USE_STATIC` true, `OpenBLAS_LIBRARIES` will then refer to a static library.)
```cmake
SET(OpenBLAS_VERSION "0.2.20.dev")
# Compute the installation prefix relative to this file.
get_filename_component(_IMPORT_PREFIX "${CMAKE_CURRENT_LIST_FILE}" PATH)
get_filename_component(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)
get_filename_component(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)
get_filename_component(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)
if(_IMPORT_PREFIX STREQUAL "/")
	set(_IMPORT_PREFIX "")
endif()
SET(OpenBLAS_INCLUDE_DIRS ${_IMPORT_PREFIX}/include)
# use dynamic import library if MSVC
if(MSVC)
	SET(OpenBLAS_LIBRARIES ${_IMPORT_PREFIX}/lib/libopenblas.dll.a)
else(MSVC)
	SET(OpenBLAS_LIBRARIES ${_IMPORT_PREFIX}/bin/libopenblas.dll)
endif(MSVC)
SET(OPENBLAS_IS_DYNAMIC true)
# if OpenBlas_USE_STATIC is true,force to use static library with MinGW
if(OPENBLAS_IS_DYNAMIC)
	if(EXISTS "${_IMPORT_PREFIX}/lib/libopenblas.a" AND OpenBlas_USE_STATIC AND NOT MSVC)
		MESSAGE(STATUS "use OpenBlas static library")
		SET(OpenBLAS_LIBRARIES ${_IMPORT_PREFIX}/lib/libopenblas.a)
		SET(OPENBLAS_IS_DYNAMIC false)
	endif()
endif(OPENBLAS_IS_DYNAMIC)
if(OPENBLAS_IS_DYNAMIC)
	SET(OpenBLAS_LIBRARIES_BIN ${_IMPORT_PREFIX}/bin/libopenblas.dll)
endif(OPENBLAS_IS_DYNAMIC)
unset(OPENBLAS_IS_DYNAMIC)
unset(_IMPORT_PREFIX)
```
While `make install` with `NO_SHARED=1`, `OpenBLASConfig.cmake` will be generated as following:

(`OpenBLAS_LIBRARIES` refers to a static library)
```cmake
SET(OpenBLAS_VERSION "0.2.20.dev")
# Compute the installation prefix relative to this file.
get_filename_component(_IMPORT_PREFIX "${CMAKE_CURRENT_LIST_FILE}" PATH)
get_filename_component(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)
get_filename_component(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)
get_filename_component(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)
if(_IMPORT_PREFIX STREQUAL "/")
	set(_IMPORT_PREFIX "")
endif()
SET(OpenBLAS_INCLUDE_DIRS ${_IMPORT_PREFIX}/include)
SET(OpenBLAS_LIBRARIES ${_IMPORT_PREFIX}/lib/libopenblas.a)
if(MSVC)
	message(STATUS "OpenBLAS_LIBRARIES(static library):${OpenBLAS_LIBRARIES}" )
	message(FATAL_ERROR "With Visual Studio, only dynamic linking is supported,please reinstall OpenBLAS without NO_STATIC=1" )
endif(MSVC)
SET(OPENBLAS_IS_DYNAMIC false)
# if OpenBlas_USE_STATIC is true,force to use static library with MinGW
if(OPENBLAS_IS_DYNAMIC)
	if(EXISTS "${_IMPORT_PREFIX}/lib/libopenblas.a" AND OpenBlas_USE_STATIC AND NOT MSVC)
		MESSAGE(STATUS "use OpenBlas static library")
		SET(OpenBLAS_LIBRARIES ${_IMPORT_PREFIX}/lib/libopenblas.a)
		SET(OPENBLAS_IS_DYNAMIC false)
	endif()
endif(OPENBLAS_IS_DYNAMIC)
if(OPENBLAS_IS_DYNAMIC)
	SET(OpenBLAS_LIBRARIES_BIN ${_IMPORT_PREFIX}/bin/libopenblas.dll)
endif(OPENBLAS_IS_DYNAMIC)
unset(OPENBLAS_IS_DYNAMIC)
unset(_IMPORT_PREFIX)
```

`OpenBLASConfig.cmake` genetated under Linux with `NO_SHARED=1` 
```cmake
SET(OpenBLAS_VERSION "0.2.20.dev")
# Compute the installation prefix relative to this file.
get_filename_component(_IMPORT_PREFIX "${CMAKE_CURRENT_LIST_FILE}" PATH)
get_filename_component(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)
get_filename_component(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)
get_filename_component(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)
if(_IMPORT_PREFIX STREQUAL "/")
    set(_IMPORT_PREFIX "")
endif()
SET(OpenBLAS_INCLUDE_DIRS ${_IMPORT_PREFIX}/include)
SET(OpenBLAS_LIBRARIES ${_IMPORT_PREFIX}/lib/libopenblas.a)
unset(_IMPORT_PREFIX)
```

### CODE REVIEW

**Comment by brada4** [comment]
Other software typically set installation path in cmake file so you can move description alone around and use libraries where they are installed.
Can you leave absolute path to original installation intact and try yours if it disappears?

**Comment by 10km** [comment]
following is  part  code from `hdf5-config.cmake`:
```
#-----------------------------------------------------------------------------
# HDF5 Config file for compiling against hdf5 build/install directory
#-----------------------------------------------------------------------------
...
get_filename_component(PACKAGE_PREFIX_DIR "${CMAKE_CURRENT_LIST_DIR}/../" ABSOLUTE)
...
#-----------------------------------------------------------------------------
# Directories
#-----------------------------------------------------------------------------
set (${HDF5_PACKAGE_NAME}_INCLUDE_DIR "${PACKAGE_PREFIX_DIR}/include" "${${HDF5_PACKAGE_NAME}_MPI_C_INCLUDE_PATH}")
```

it also use `get_filename_component` command get installation path and set to `${HDF5_PACKAGE_NAME}_INCLUDE_DIR`,
for detail about `CMAKE_CURRENT_LIST_DIR` ,
see also https://cmake.org/cmake/help/v3.8/variable/CMAKE_CURRENT_LIST_DIR.html

**Comment by martin-frbg** [comment]
If I understand this correctly, this change does not affect building or installation as such, it just makes it easier (for users of cmake) to link to the installed version after moving it around on the target system(s) (?).
CMAKE_CURRENT_LIST_DIR appears to be available in cmake 2.8.5 already (that being the minimal version currently required by the toplevel CMakeLists.txt for building) so that is fine as well.
Still my suggestion is to postpone the merge "just in case" until after 0.2.20 is released (assuming this will have happened by the end of this week)

**Comment by martin-frbg** [comment]
On second thought, it might be better to check first if CMAKE_CURRENT_LIST_DIR is actually defined - as it seems there are a few users of OpenBLAS still working with RHEL5 installations that may have come with even earlier versions of cmake.

**Comment by 10km** [comment]
@martin-frbg I see, should use CMAKE_CURRENT_LIST_FILE instead of CMAKE_CURRENT_LIST_DIR, CMAKE_CURRENT_LIST_FILE  be available in cmake 2.6

**Comment by brada4** [comment]
It is absolutely not typical on Linux to move around installed files. And your config is very unfriendly to LSB, i.e .h .so .cmake not in subdirectories.

**Comment by martin-frbg** [comment]
@brada4 I am not sure where the proposed change would make the config worse than it currently is.
What could be a problem (and I did not notice it earlier) is the hardcoding of "/lib" in the new library path
where it might be "lib64" on at least some systems (but again I have not checked whether the current form of that config file would allow for that).

**Comment by brada4** [comment]
If you have multiple openblas cmake files you may want to copy one with preferred version into your current build directory.
With proposed change you cannot target "default" build in /opt/OpenBLAS/ with cmake. cmake will sniff around current directory, hopefully finding something like blas in (/usr)/lib*/(openblas/)

**Comment by 10km** [comment]
@martin-frbg about 'lib64' in some sytem(such as centos),cmake have solution ,see also https://cmake.org/cmake/help/cmake2.6docs.html#prop_global:FIND_LIBRARY_USE_LIB64_PATHS

**Comment by 10km** [comment]
following is structure of ~/Desktop/caffe-static on my computer.
  
	~/Desktop/caffe-static
	├── release
	│   ├── boost_linux_x86_64
	│   ├── bzip2_linux_x86_64
	│   ├── caffe-ssd_linux_x86_64
	│   ├── gflags_linux_x86_64
	│   ├── glog_linux_x86_64
	│   ├── hdf5_linux_x86_64
	│   ├── leveldb_linux_x86_64
	│   ├── lmdb_linux_x86_64
	│   ├── OpenBLAS_linux_x86_64
	│   ├── opencv_linux_x86_64
	│   ├── protobuf_linux_x86_64
	│   └── snappy_linux_x86_64
	├── source
	│   ├── boost-1.58.0
	│   ├── bzip2-1.0.5
	│   ├── bzip2-1.0.6
	│   ├── caffe-ssd
	│   ├── gflags-2.2.0
	│   ├── glog-0.3.5
	│   ├── hdf5-1.8.16
	│   ├── leveldb-1.18
	│   ├── lmdb-0.9.21
	│   ├── OpenBLAS-0.2.18
	│   ├── opencv-2.4.13.2
	│   ├── protobuf-3.3.1
	│   └── snappy-master
	└── tools
		└── cmake-3.8.2-Linux-x86_64

For building `caffe` project,I build all dependent projects under 'source' and install them to 'release' folder.
All projects's installation folder can be moved but OpenBLAS      
If values of `OpenBLAS_INCLUDE_DIRS` and `OpenBLAS_LIBRARIES` isn't hardcoding of an absolute path, the 'caffe-static' folder can be move to another foler  or computer for building. and, the OpenBLAS's installation folder can be move or copy for reusing independently. 
Otherwise,`OpenBLAS_INCLUDE_DIRS` and `OpenBLAS_LIBRARIES` will be invalid while the folder moved.

**Comment by brada4** [comment]
The degradations start once you intend to use any of libraries with cmake spec installed by system packages in /usr. Also if you build OpenBLAS with 'make' and not 'cmake'

**Comment by 10km** [comment]
@brada4 
you're right.
actually, I build OpenBLAS with make(either Windows or Linux),because OpenBLAS's MakeLists.txt is incomplete yet.

	
	install_path=$OPENBLAS_INSTALL_PATH
	echo install_path:$install_path
	pushd $SOURCE_ROOT/$OPENBLAS_FOLDER
	make clean
	exit_on_error
	make -j $MAKE_JOBS CC=$MAKE_C_COMPILER NOFORTRAN=1 NO_SHARED=1 DYNAMIC_ARCH=1
	exit_on_error
	remove_if_exist $install_path
	make install PREFIX=$install_path NO_LAPACKE=1 NO_SHARED=1
	exit_on_error
	popd

**Comment by brada4** [comment]
Indeed it is very good on a single-user system. It is not acceptable on multi-user system to make up 1GB binary blob from thin air and throw it into user group's machine.
Your change breaks any LSB expectations and in addition smokescreens default 'make' build.
One file with few variables is much easier to patch with actual lib locations inside package.

PS I build all sorts of distribution packages for food.

**Pull request closed without merging**
