### PR TITLE
remove unused 'levelness' parameter from num_cpu_avail()

### PR DESCRIPTION
**Pull request by brada4**
and remove it from all callers, probably moderating the thread limit for small sets could go to interface/?
i have some doubts about extra roll with same num_cpu_avail() in kernel/ ... shouldnt it be all in one place?

### CODE REVIEW

**Comment by martin-frbg** [comment]
While this parameter has been unused for ages, I am not sure if it is worth changing so many files just to get rid of it ? (Seems in GotoBLAS2-1.08 it was used to disable multithreading for some callers, but that code was already removed in 1.13)

**Comment by martin-frbg** [comment]
PS callers in kernel/* are a handful of cases where parallelization is implemented in cpu-specific code.

**Comment by brada4** [comment]
Rationale that in this place integer parameter does not have any future use or so. interface/ indeed can be perfectly calibrated per function x coretype

**Comment by brada4** [comment]
would it help reinstating old prototype with warning?

**Pull request closed without merging**
