### PR TITLE
Minor fixes

### PR DESCRIPTION
**Pull request by brada4**
Rewrite one pair of identical branches
Clear few dead trailing codes
Eliminate two unused variables
All from clang checker, strangely missed previously.

### CODE REVIEW

**Comment by martin-frbg** [comment]
Close and reopen should also work to trigger a retest, no need to add otherwise unneeded changes.
Not sure what makes that one appveyor test hit the 1 hr limit every now and again (and finish in under 55 minutes otherwise)

**Comment by brada4** [comment]
Point taken of one subject per PR.

**Comment by martin-frbg** [comment]
I'd still prefer to see the benchmark fixed in a separate PR, and the "take out unreachable branch to retrigger CI" removed as it only makes the code harder to read ? (Also it will probably mess up "git blame" which currently allows to trace the actual "if 0" code change to issue 130 (and I am not entirely sure if that old change was even an appropriate fix for the issue)

**Comment by brada4** [comment]
OK

**Comment by martin-frbg** [comment]
BTW where did the additional "+2" (as in "k+2") come from in your patch for 1474 ?

**Pull request closed without merging**
