### PR TITLE
cmake: update minimum_required cmake version

### PR DESCRIPTION
**Pull request by haampie**
It's better to enable https://cmake.org/cmake/help/latest/policy/CMP0042.html#policy:CMP0042 than to explicitly set CMAKE_MACOSX_RPATH, since users may want to set the latter from the command line.

### CODE REVIEW

**Comment by martin-frbg** [comment]
Thanks - I'm always a bit hesitant when it comes to tightening minimum version requirements, as at least "historically" some users were unable to update the systems they worked on. The original CMakeLists.txt under lapack-netlib are not used when building LAPACK as a part of OpenBLAS, so I think this can be deferred to 0.3.29 (?)

**Comment by haampie** [comment]
Ah, I saw some `add_subdirectory` and assumed that's how it worked, sorry for the misunderstanding.

In that case let me use the most conservative option: `cmake_policy(SET CMP0042 NEW)`

**Comment by conradsnicta** [comment]
@martin-frbg @haampie I'd suggest to bump the min version of CMake, rather than messing around with policies.

Using ancient versions of CMake adds to the technical debt and increases the maintenance burden.

CMake 2.8.5 (currently required by OpenBLAS) is truly prehistoric, released circa 2010.  
Cmake 3.0 (released in 2014) is generally known as the starting point for "modern" CMake.

A good indicator of the oldest allowable version of CMake would be across old mainstream long-term linux distros (Red Hat, Ubuntu, Debian) that are still within their normal support period:

* RHEL 8 has CMake 3.26.5
* Debain 11 has CMake 3.18.4
* Ubuntu 20.04 LTS has 3.16.3

This suggests CMake 3.16 as the oldest baseline version.  Anything older than that has a rapidly diminishing number of users.

(Similar comment applies to ancient versions of GCC and Clang.  In my view, the required workarounds for out-of-support compilers are simply not worth it.)

**Comment by martin-frbg** [comment]
turns out that updating the minimum required cmake version (or adding even more cmp... policies) is also necessary for cross-compilations with the current Android NDK (r27), so I've finally hacked conradsnicta's suggestion into your PR branch

**Comment by haampie** [comment]
great

**Pull request merged**
