### PR TITLE
Install pkg-config files

### PR DESCRIPTION
**Pull request by isuruf**
Fixes https://github.com/xianyi/OpenBLAS/issues/598

### CODE REVIEW

**Comment by isuruf** [comment]
Thanks

**Comment by IvanUkhov** [comment]
@isuruf, that you for this work! I’m curious why the installed pkg-config files are `blas.pc`, `cblas.pc`, and `lapack.pc`, not `openblas.pc`. Will pkg-config be able to find the library by the name `openblas` as well? If not, `openblas.pc` perhaps should also be provided. What do you think?

**Comment by isuruf** [comment]
I used the names netlib uses so that when openblas is installed, it can provide `blas`, `cblas` and `lapack` as the default implementation. You are correct that `openblas` will not be found. `openblas.pc` can be provided. Do you think we should remove `blas.pc`, etc and keep only `openblas.pc`?

**Comment by IvanUkhov** [comment]
In my opinion, `openblas.pc` is essential; the rest are optional. It’s the library called `openblas` that we’re installing, not something else, and, therefore, there should be a pkg-config file for this very library. Otherwise, there’ll be no natural way to test the availability of and link to specifically OpenBLAS instead of some arbitrary BLAS/LAPACK provider.

**Pull request merged**
