### PR TITLE
Include version number in openblas_get_config output

### LINKED ISSUE #1889: ENH: add an extension to get the library version
I could not find an interface to query the version number (i.e. 0.3.3, 0.3.0) of OpenBLAS.

In the process I found the [wiki page](https://github.com/xianyi/OpenBLAS/wiki/OpenBLAS-Extensions) for the extensions, but there is not one for the version. Even using `strings *.so` I could not find it.

### PR DESCRIPTION
**Pull request by martin-frbg**
fixes #1889

### CODE REVIEW

**Comment by brada4** [comment]
What about starting with OPENBLAS like in:
http://www.netlib.org/lapack/explore-html/d8/d8b/_l_a_p_a_c_k__version_8f_source.html

**Comment by martin-frbg** [comment]
No preference for either option, except "OpenBLAS" is one byte more expensive than "VERSION" :smile: and one would not expect openblas_get_config() to return anything other than OpenBLAS info I guess ? (But I have never been good at marketing, so your suggestion is probably valid)

**Comment by brada4** [comment]
API would be If you scan for OpenBLAS it is the sort of "new API" that has version number, otherwise assume past.

**Comment by brada4** [comment]
If we trip the thin border between marketing and industrial espionage - ATLAS just prints a rich banner page with version

**Pull request merged**
