### PR TITLE
Add some refines and optimizations for LoongArch.

### PR DESCRIPTION
**Pull request by yinshiyou**
1) Fixed a output format problem for benchmark.
2) Refine LA build check process.
3) Add s/ddot optimizations.

### CODE REVIEW

**Comment by martin-frbg** [comment]
Thanks. So we don't need to check if the compiler comes with the lsx intrinsics header anymore ?

**Comment by yinshiyou** [comment]
> Thanks. So we don't need to check if the compiler comes with the lsx intrinsics header anymore ?

Thanks!  I think c_check has checked the inline assembler,  and the code in kernel/loongarch use assembler too.
So it should not disable assembler optimization for compiler which unsupport intrinsics but support raw assembler.

**Comment by martin-frbg** [comment]
I'm just confused as it is only a few months ago that this test was added (#4127) - I do not know the LoongArch64 ecosystem well, so I can't tell if presence of the intrinsics header is a necessary sign that the toolchain "really" knows how to handle LSX instructions. (Or maybe @XiWeiGu is/was preparing the ground for intrinsics-based kernels in the future ?)

**Comment by XiWeiGu** [comment]
On LoongArch64, if an intrinsics-based kernel is not used, there is no need for intrinsics header checks. Currently, LoongArch64 does not have an intrinsics-based kernel, and there are no plans to add one in the future. Therefore, intrinsics header checks can be removed.

**Comment by martin-frbg** [comment]
Thank you.

**Pull request merged**
