### PR TITLE
Fixed a few more unnecessary calls to num_cpu_avail.

### PR DESCRIPTION
**Pull request by oon3m0oo**
I don't have as many benchmarks for these as for gemm, but it should still
make a difference for small matrices.

### CODE REVIEW

**Comment by martin-frbg** [comment]
@ashwinyes as this touches thunderx code...

**Comment by oon3m0oo** [comment]
@ashwinyes gentle ping on this.  It shouldn't be too terribly controversial since the calls are essentially moot when threading isn't selected.  Please do check the logic, though!

**Comment by martin-frbg** [comment]
Perhaps you could leave the arm64 parts of the PR until later if ashwinyes is busy ? While the changes do look harmless to me, I do not want to be responsible for breaking his Cavium server platform _another time_

**Comment by ashwinyes** [comment]
Sorry for the delayed response.

I dont have any issue with this PR. 

You may go ahead with the commit.

**Comment by martin-frbg** [comment]
Thanks for the review, merging now.

**Pull request merged**
