### PR TITLE
Add implementation of WhereAmI() to support NO_AFFINITY=0 on ARM64

### LINKED ISSUE #4623: Build fails on Ubuntu 20.04 aarch64 with undefined reference to 'WhereAmI'
### Environment
```
- version: OpenBLAS-0.3.7
- OS: Ubuntu 20.04.2 LTS (Focal Fossa)
- CPU details:
Architecture: aarch64
CPU op-mode(s): 64-bit
Byte Order: Little Endian
CPU(s): 64
On-line CPU(s) list: 0-63
Thread(s) per core: 1
Core(s) per socket: 64
Socket(s): 1
NUMA node(s): 8
Vendor ID: 0x70
Model: 2
Stepping: 0x1
BogoMIPS: 100.00
L1d cache: 2 MiB
L1i cache: 2 MiB
L2 cache: 256 MiB
NUMA node0 CPU(s): 0-7
NUMA node1 CPU(s): 8-15
NUMA node2 CPU(s): 16-23
NUMA node3 CPU(s): 24-31
NUMA node4 CPU(s): 32-39
NUMA node5 CPU(s): 40-47
NUMA node6 CPU(s): 48-55
NUMA node7 CPU(s): 56-63
Vulnerability Itlb multihit: Not affected
Vulnerability L1tf: Not affected
Vulnerability Mds: Not affected
Vulnerability Meltdown: Mitigation; PTI
Vulnerability Spec store bypass: Vulnerable
Vulnerability Spectre v1: Mitigation; __user pointer sanitization
Vulnerability Spectre v2: Vulnerable
Vulnerability Srbds: Not affected
Vulnerability Tsx async abort: Not affected
Flags: fp asimd evtstrm crc32 cpuid
```
### Issue description
Encountered a build error when compiling OpenBLAS on aarch64 architecture. The specific error message is
```
/usr/bin/ld: ../libopenblas_armv8p-r0.3.7.a(init.o): in function `gotoblas_set_affinity':
init.c:(.text+0xf8): undefined reference to `WhereAmI'
/usr/bin/ld: ../libopenblas_armv8p-r0.3.7.a(init.o): in function `get_node':
init.c:(.text+0x14c): undefined reference to `WhereAmI'
collect2: error: ld returned 1 exit status
make[1]: *** [Makefile:146: zblat1] Error 1
make[1]: *** Waiting for unfinished jobs....
/usr/bin/ld: ../libopenblas_armv8p-r0.3.7.a(init.o): in function `gotoblas_set_affinity':
init.c:(.text+0xf8): undefined reference to `WhereAmI'
/usr/bin/ld: ../libopenblas_armv8p-r0.3.7.a(init.o): in function `get_node':
init.c:(.text+0x14c): undefined reference to `WhereAmI'
collect2: error: ld returned 1 exit status
make[1]: *** [Makefile:143: cblat1] Error 1
```
### Steps to Reproduce
1. Set the following configuration in Makefile.rule:
   ```
   NUM_THREADS = 64
   USE_OPENMP = 1
   NO_AFFINITY = 0
   ```
2. Run the following build command:
   ```
   nohup make NO_AFFINITY=0 -j32 &> makelog &
   ```

### Error Message
The build fails with the following output:
```
undefined reference to 'WhereAmI'
```

### Log Files and output
see  the attachment

### PR DESCRIPTION
**Pull request by martin-frbg**
fixes #4623

### CODE REVIEW

**Comment by NickelWenzel** [comment]
@martin-frbg this change might have broken windows arm64 builds, see the failed azure pipelines in this [PR](https://github.com/microsoft/vcpkg/pull/40911/checks?check_run_id=30014623379) which prevents from bumping the version to 0.3.28 in the vcpkg port.

At least that is what i see in the attached log.

```
Change Dir: 'D:/b/openblas/arm64-windows-dbg'

Run Build Command(s): "C:/Program Files/Microsoft Visual Studio/2022/Enterprise/Common7/IDE/CommonExtensions/Microsoft/CMake/Ninja/ninja.exe" -v -v -j33 install
[1/1740] C:\PROGRA~1\MICROS~1\2022\ENTERP~1\VC\Tools\MSVC\1438~1.331\bin\Hostx64\arm64\cl.exe    -ID:\b\openblas\src\v0.3.28-8b4f07f037.clean -ID:\b\openblas\arm64-windows-dbg /nologo /DWIN32 /D_WINDOWS /utf-8 /MP   -DGEMM_GEMV_FORWARD -DNO_LAPACK -DNO_LAPACKE -DNO_WARMUP -DMAX_CPU_NUMBER=0 -DMAX_PARALLEL_NUMBER=1 -DNO_AFFINITY -DVERSION="\"0.3.28\"" -DBUILD_SINGLE -DBUILD_DOUBLE -DBUILD_COMPLEX -DBUILD_COMPLEX16 /D_DEBUG /MDd /Z7 /Ob0 /Od /RTC1 /showIncludes /Fointerface\CMakeFiles\interface.dir\CMakeFiles\cnrm2.c.obj /Fdinterface\CMakeFiles\interface.dir\ /FS -c D:\b\openblas\arm64-windows-dbg\interface\CMakeFiles\cnrm2.c
FAILED: interface/CMakeFiles/interface.dir/CMakeFiles/cnrm2.c.obj 
C:\PROGRA~1\MICROS~1\2022\ENTERP~1\VC\Tools\MSVC\1438~1.331\bin\Hostx64\arm64\cl.exe    -ID:\b\openblas\src\v0.3.28-8b4f07f037.clean -ID:\b\openblas\arm64-windows-dbg /nologo /DWIN32 /D_WINDOWS /utf-8 /MP   -DGEMM_GEMV_FORWARD -DNO_LAPACK -DNO_LAPACKE -DNO_WARMUP -DMAX_CPU_NUMBER=0 -DMAX_PARALLEL_NUMBER=1 -DNO_AFFINITY -DVERSION="\"0.3.28\"" -DBUILD_SINGLE -DBUILD_DOUBLE -DBUILD_COMPLEX -DBUILD_COMPLEX16 /D_DEBUG /MDd /Z7 /Ob0 /Od /RTC1 /showIncludes /Fointerface\CMakeFiles\interface.dir\CMakeFiles\cnrm2.c.obj /Fdinterface\CMakeFiles\interface.dir\ /FS -c D:\b\openblas\arm64-windows-dbg\interface\CMakeFiles\cnrm2.c
D:\b\openblas\src\v0.3.28-8b4f07f037.clean\common_arm64.h(60): error C2065: '__asm__': undeclared identifier
D:\b\openblas\src\v0.3.28-8b4f07f037.clean\common_arm64.h(60): error C2143: syntax error: missing ';' before 'volatile'
[2/1740] C:\PROGRA~1\MICROS~1\2022\ENTERP~1\VC\Tools\MSVC\1438~1.331\bin\Hostx64\arm64\cl.exe    -ID:\b\openblas\src\v0.3.28-8b4f07f037.clean -ID:\b\openblas\arm64-windows-dbg /nologo /DWIN32 /D_WINDOWS /utf-8 /MP   -DGEMM_GEMV_FORWARD -DNO_LAPACK -DNO_LAPACKE -DNO_WARMUP -DMAX_CPU_NUMBER=0 -DMAX_PARALLEL_NUMBER=1 -DNO_AFFINITY -DVERSION="\"0.3.28\"" -DBUILD_SINGLE -DBUILD_DOUBLE -DBUILD_COMPLEX -DBUILD_COMPLEX16 /D_DEBUG /MDd /Z7 /Ob0 /Od /RTC1 /showIncludes /Fointerface\CMakeFiles\interface.dir\CMakeFiles\sasum.c.obj /Fdinterface\CMakeFiles\interface.dir\ /FS -c D:\b\openblas\arm64-windows-dbg\interface\CMakeFiles\sasum.c
FAILED: interface/CMakeFiles/interface.dir/CMakeFiles/sasum.c.obj 
```

[install-arm64-windows-dbg-out.log](https://github.com/user-attachments/files/17309442/install-arm64-windows-dbg-out.log)
[install-arm64-uwp-dbg-out.log](https://github.com/user-attachments/files/17309618/install-arm64-uwp-dbg-out.log)

@JAicewizard FYI

**Comment by martin-frbg** [comment]
Ah, that addition probably needs to be conditional on `#ifndef MSVC` as Visual Studio does not handle the inline assembly (nor its GNU/AT&T-style syntax). Unfortunately I do not have WoA hardware so I have no idea if there are further obstacles to expect

**Comment by NickelWenzel** [comment]
The canonical way looking at the other `common_xxx.h` headers seems to be to surround `WhereAmI` by `#ifndef NO_AFFINITY`.

I opened a [PR](https://github.com/OpenMathLib/OpenBLAS/pull/4926) for this. Feel free to have a look and as this is my first contribution (to open source ever) don't hesitate if I didn't set sth up correctly.

**Comment by JAicewizard** [comment]
Oh yeah I still had that PR open, I had no idea how to debug the faillure. Thanks for noticing the issue and being able to diagnose it!

**Comment by martin-frbg** [comment]
That's slightly different - when "NO_AFFINITY" is not set, the WhereAmI() function is simply not needed. In your case, it is that particular compiler that does not like the way WhereAmI() is implemented (e.g. LLVM would probably compile it without complaining) - but cpu affinity handling is not implemented in the Windows version of the blas_server code anyway, so in practice either `ifndef` should work.

**Comment by martin-frbg** [comment]
C_MSVC actually - sorry. Now hopefully fixed in PR #4927

**Comment by martin-frbg** [comment]
@NickelWenzel sorry, had not realized that you opened the PR against OpenBLAS rather than the vpkpg port. Let's go with your version of the fix then.

**Pull request merged**
