### PR TITLE
Revert "Add basic support for the (mostly x86_64 compatible) Elbrus E2000 architecture"

### PR DESCRIPTION
**Pull request by martin-frbg**
Reverts xianyi/OpenBLAS#3518

### CODE REVIEW

**Comment by makise-homura** [comment]
I have read #3551, and what I see there just makes me kinda losing faith to humanity at all, and to FOSS community (or at least people who mostly involved there in discussion), in certain.

I am one of the developers of Elbrus systems (actually PCBs using it, and software used in such a systems). And I feel no guilt in saying that. And in the same time, I absolutely against the war that Putin started in Ukraine. Mostly, for several reasons I count it as a most stupid decision of him (and still personally hate him for ruining the Russian economy and connections to other world). How dare I talk like that, you ask? Simple. It's **two distinct things irrelevant to each other**, that's why.

But, the thing I insist on taking as one of the rules of FOSS philosophy, and won't decline myself at any case: *Free Software is about freedom*, no political, ethnical, ideological, religional, or any other means shall be a reason of any action taken in maintaining the code. It's OK if Elbrus support is removed due to, say, this CPU being obsolete, or due to this support is incompatible with other code and makes it unmaintainable. But it is completely not OK if it is removed based on any political motivation. Don't fool yourself: everybody lies. Putin lies, Biden lies, Zelensky lies, everyone others too, and please, don't be misleaded by anything that may, or even must, be lie. In the case of FOSS, don't count yourself as a citizen of a certain country, be smarter than that, count yourself as a human of the planet Earth, and the participant of FOSS community. A contributor, not a warrior.

You know, I contributed to a product ([ftl-sdk](https://github.com/microsoft/ftl-sdk/pull/91)) of Microsoft, which is now banned Russia, but I have no regrets of making my contribution. I participate in developing [Taisei Project](https://github.com/taisei-project/taisei), a game who has a lot of contributions from a person from Ukraine, and I feel no hatred or other negative emotions for him (just feel compassionate to him because of all the suffering he experiences today because of that war). I help developing BOINC and BOINC tasks for the sake of science that all humanity would wield, like, say, knowing how we could fight not each other, but SARS-CoV-2, or learn about fundamental particles, black holes and evolution of the Universe. And a serious part (but not the whole) of my contribution is of making this stuff work on Elbrus, not because I was ordered to, but because I want to make world better, and Elbrus more available and interesting to end users.

As a person who sees how this goes internally, I can say that what said in, say, [this comment](https://github.com/xianyi/OpenBLAS/issues/3551#issuecomment-1058686465) is mostly an exaggeration, a speculation, an intentional lie, or all of these. (If anyone needs certain details, feel free to ask me.) If that's a sort of information that western people unconditionally treat as truth, I doubt that many things you heard of Ukraine-Russian war are true too, and wonder what percent of it.

Specifically,
* Elbrus is not used "only by military" (it's quite funny that military likes home-grown SPARC much more than E2K; I guess I can't disclose certain details, but any public info is quite easy googled). There are non-military customers, both national (like Russian Post, Police, and Social Welfare) and private business, and even persons. It doesn't have such a wide spread like x86_64; but it might be compared to MIPS or RISC V availability in Russia.
* Elbrus is not a "closed secret architecture". It has a CC-BY licensed [programming guide](http://ftp.altlinux.org/pub/people/mike/elbrus/docs/elbrus_prog/html/index.html) (in Russian), it has relatively wide community and public [Telegram channels](https://t.me/e2k_chat), you even have an option to acquire free and virtually unlimited (non-root) access to demo stations based on 8C and 8CV CPUs: just write [here](https://t.me/elbrus_gensokyo) if you're interested, no matter where in the world you are.
* Yes, it's hard to buy Elbrus at a nearest convenience store, I admit. Try then to buy, like, AST2600 demo board, professional high-speed multichannel ADC board, or a board of top-level Altera/Intel or Xilinx FPGA. You find that it's much harder than to buy Elbrus motherboard (check [imaxai.ru](https://imaxai.ru/) if you're interested in buying it actually).
* Most of us, Elbrus developers, do porting software not because government, military, or Putin himself ordered us to; no, it's a complete nonsense. We do it because we like it, and it's fun to run a certain software on a computer with a sort of unique architecture. Well, we port games (GZDoom, DOOM 3, OpenMW, OpenGothic, The Dark Mod, Taisei Project and so on), benchmarks, test suites, science and math software. It's what *we* want, not military.
* last, but not least: OpenBLAS is not quite a point to deny using Elbrus in military environment: there is EML, Elbrus Math Library, which is another, home-grown BLAS implementation. They would just use that, OpenBLAS is no critical for military, so no positive outcome (like making Russian army less effective) can be reached; but negative one is obvious. Such a precedent is a point where FOSS community could fall into being a bunch of mindwashed individuals fighting each other on political grounds, rather from being a solid community who collaborates rather than fights.

Based on that, I consider reverting the addition of E2K support from OpenBLAS a highly toxic possibility, and ask for this PR to be closed without merging.

**Comment by AlphaHot** [comment]
This is a very dangerous precedent.

**Comment by sfsharapov** [comment]
@martin-frbg, you've reverted the commit with a patch based on a issue opened by a bot. The profile which slandered to Russia is a newly created one.

How your foreign partners could be OK with that? If you're going to make a judgement in politics please try to listen position of every part of the conflict. Even using those media which are blocked by your governments. Russians reportedly do the same thing nowadays. There are a lot of fake news, unfortunately. Special military operation which is currently held by Russian armed forces has very clear goals to achieve and based on acceptable principles for peacemakers. On the other hand, how that matters in FOSS world?

I'm agree, that the choice _absolutely_ does belong to the developers. However I would ask you to seriously consider the issue and opinions of all people involved here.

**Comment by martin-frbg** [comment]
@makise-homura thank you very much for providing information on the technical background. Indeed the primary point of creating this PR was to attract comment from people actually using OpenBLAS and/or Elbrus (in contrast to the ill-fated issue thread that got shared on social media).
@sfsharapov I have not reverted anything yet. The second reason for this PR was to highlight exactly what code would be removed if we were to follow the polite suggestion made by @rubicon1042 (and I see no reason to assume s/he is a bot just because the github account was created to post the issue). I think it should be fairly obvious that this is an overblown issue, 
as OpenBLAS will function just the same with or without the patch, i.e. without any Elbrus-specific optimizations. The primary practiical difference should be that with the PR reverted, it would again be necessary to build with TARGET=GENERIC.

**Pull request closed without merging**
