### PR TITLE
[WIP] Add ica(min,max)/isa(min,max) workaround for a bug in gcc 4.x/5.x

### LINKED ISSUE #2254: Compiler Failure on POWER8 with /kernel/power/i{c,d,s,z}a{min,max}.c
I updated my installations on my POWER8 machine and since version 0.3.6 up to the current development branch, the build process fails with: 

```
$ make  MAKE_NB_JOBS=1
...
cc -c -Ofast -mcpu=power8 -mtune=power8 -mvsx -malign-power -DUSE_OPENMP -fno-fast-math -fopenmp -DMAX_STACK_ALLOC=2048 -fopenmp -Wall -m64 -DF_INTERFACE_GFORT -fPIC -DSMP_SERVER -DUSE_OPENMP -DNO_WARMUP -DMAX_CPU_NUMBER=160 -DMAX_PARALLEL_NUMBER=1 -DVERSION=\"0.3.8.dev\" -DASMNAME=isamax_k -DASMFNAME=isamax_k_ -DNAME=isamax_k_ -DCNAME=isamax_k -DCHAR_NAME=\"isamax_k_\" -DCHAR_CNAME=\"isamax_k\" -DNO_AFFINITY -I.. -UDOUBLE  -UCOMPLEX -UCOMPLEX -UDOUBLE -DUSE_ABS  -UUSE_MIN ../kernel/power/isamax.c -o isamax_k.o
../kernel/power/isamax.c: In function ‘siamax_kernel_64’:
../kernel/power/isamax.c:288:1: internal compiler error: in build_int_cst_wide, at tree.c:1210
 }
 ^
Please submit a full bug report,
with preprocessed source if appropriate.
See <http://bugzilla.redhat.com/bugzilla> for instructions.
Preprocessed source stored into /tmp/ccriHyPV.out file, please attach this to your bugreport.
make[1]: *** [isamax_k.o] Error 1
make[1]: Leaving directory `/root/OpenBLAS/kernel'
make: *** [libs] Error 1

```

OS Details:
CentOS 7.6 ppc64el, gcc 4.8.5, gfortran 4.8.5, IBM POWER8 LC822

### PR DESCRIPTION
**Pull request by martin-frbg**
fixes #2254

### CODE REVIEW

**Comment by martin-frbg** [comment]
This was tested on various ppc hosts in the unicamp.br minicloud, so not sure what is (still) up with travis. Will resubmit a clean PR that will leave the ppc CI job in the naughty corner for now.

**Comment by isuruf** [comment]
@jayfurmanek, have you run into this before?

**Comment by martin-frbg** [comment]
Hmm. Maybe I was too quick. gcc8.3 on power8 (ubuntu 19.04) is showing a number of lapack-test
failures for single-precision complex. Checking to see if -O0 for icamin/icamax is necessary and sufficient to fix this as well. 
Update: yes fixed. so problem apparently still there with 8.3, just shifted from ICE to wrong-code.

**Comment by jayfurmanek** [comment]
Can't say that I have. It's hard to tell what Travis is doing. Is it just hanging?

**Comment by isuruf** [comment]
Yes, it's just hanging. I started a new build in my fork and it's going back and forth between queued and booting phases for a while now. https://travis-ci.org/isuruf/OpenBLAS/jobs/585778972

**Comment by martin-frbg** [comment]
Seems so. We normally use QUIET_MAKE to avoid aborts due to too much output, I removed that here to see where it was failing, but this time something appears to be fundamentally broken in the travis cloud. Note this was working fine until a few weeks ago.

**Comment by jayfurmanek** [comment]
I have actually seen *that* recently: Travis bounce between queue and boot phases on various repos. Eventually it seems to right itself, though.
Current status says "partially degraded" but it doesn't look related. is there a way to open a service request?

**Comment by isuruf** [comment]
@martin-frbg, removing `travis_wait` fixed the ppc64le issue.

**Comment by isuruf** [comment]
It didn't fix the issue. It shows the error which is an ICE.

```
../kernel/power/caxpy.c:61:33: internal compiler error: in rs6000_emit_le_vsx_move, at config/rs6000/rs6000.c:9157
```

https://travis-ci.org/isuruf/OpenBLAS/jobs/585796701#L4616-L4625

**Comment by jayfurmanek** [comment]
That's still showing `-Ofast` though. I thought it should it be `-O0` with this workaround.

**Comment by isuruf** [comment]
The failing C files are different. Looks like this workaround is needed for `caxpy.c` and `cdot.c` as well.

**Comment by martin-frbg** [comment]
Strange. The gcc 5.4 build (Ubuntu 16) passed in the unicamp.br minicloud.
But I see now that it is the DYNAMIC_ARCH portion building for POWER9 that is encountering ICEs in cdot and caxpy, my 5.4 test build was power8 only until now. (And the ICE does not occur with 8.3.0)

**Comment by edelsohn** [comment]
This is a compiled bug and should be opened as an issue in GCC Bugzilla with a self-contained test case. GCC never should ICE.

This should not be worked around with lower optimization level.  That is appalling.

**Comment by martin-frbg** [comment]
> This is a compiled bug and should be opened as an issue in GCC Bugzilla with a self-contained test case. GCC never should ICE.
> This should not be worked around with lower optimization level. That is appalling.

Filing an issue in the GCC Bugzilla is not going to help people who are stuck with outdated versions of the compiler (RHEL seems to be worst in this regard but I guess that is IBM's own backyard now). And there is still some doubt if the gcc optimizer could be tripping over an actual coding error.

**Comment by jayfurmanek** [comment]
RH backports fixes, and yeah, they can't do that if they don't know about it.

**Comment by martin-frbg** [comment]
superseded by #2263

**Pull request closed without merging**
