### PR TITLE
Fix the integer overflow issue for large matrix size

### PR DESCRIPTION
**Pull request by ewanglong**
Signed-off-by: Wang, Long <long1.wang@intel.com>

We found and fixed this issue. Please help review it.

### CODE REVIEW

**Comment by wjc404** [comment]
What about changing to "unsigned long long" which is at least 64-bit ?

**Comment by ewanglong** [comment]
> What about changing to "unsigned long long" which is at least 64-bit ?

Thanks for review. I computed 64-bit data can handle matrix computing about 3 millions x 3 millions x 3 millions. It should be enough. Is there any real use case to process thus huge size matrix over it?

**Comment by ewanglong** [comment]
> What about changing to "unsigned long long" which is at least 64-bit ?

Thanks for review. For x86 platform, unsigned long is 64 bit length. It's enough to handle large matrix computing reaching 3 millions x 3 millions x 3 millions.

**Comment by ewanglong** [comment]
> > What about changing to "unsigned long long" which is at least 64-bit ?
> 
> Thanks for review. For x86 platform, unsigned long is 64 bit length. It's enough to handle large matrix computing reaching 3 millions x 3 millions x 3 millions.

Below is quick checking data length by attached code. 

Signed    : Size                    Min                    Max
--------------------------------------------------------------
char      :    1                   -128                    127
short     :    2                 -32768                  32767
int       :    4            -2147483648             2147483647
long      :    8   -9223372036854775808    9223372036854775807
long long :    8   -9223372036854775808    9223372036854775807

Unsigned  : Size                    Min                    Max
--------------------------------------------------------------
char      :    1                      0                    255
short     :    2                      0                  65535
int       :    4                      0             4294967295
long      :    8                      0   18446744073709551615
long long :    8                      0   18446744073709551615

Miscellaneous sizes:
--------------------------------------------------------------
Single precision float:                                      4
Double precision float:                                      8
size_t:                                                      8
ssize_t:                                                     8

**Comment by wjc404** [comment]
(I don't know whether the answer below is correct)
Screenshot_20191120_181026_com huawei browser

**Comment by martin-frbg** [comment]
32bit operating systems would currently see SkylakeX kernels replaced by Nehalem as fallback so it would not be an issue there. However Microsoft still appears to use just 4 bytes for "unsigned long" so "unsigned long long" (or uint64_t) would appear to be the safest solution.

**Comment by ewanglong** [comment]
"unsigned long long" was committed.

**Comment by martin-frbg** [comment]
Thanks for finding and fixing this

**Pull request merged**
