### PR TITLE
Fix SBGEMM unit test to handle zero elements.

### PR DESCRIPTION
**Pull request by ChipKerchner**
Fix SBGEMM unit test to handle zero elements - since malloc zero bytes fails on some systems.

### CODE REVIEW

**Comment by ChipKerchner** [comment]
Fixes malloc(0) failing for AIX.

**Comment by martin-frbg** [comment]
Hmm, that's annoying. M,N,K equal 0 might be a valid corner case to test, though not that important.

**Comment by ChipKerchner** [comment]
I agreed.  I say that we leave that corner case for another PR?

**Comment by ChipKerchner** [comment]
Fixed to handle zero elements.

**Comment by ChipKerchner** [comment]
GEMV returns an error for zero elements.

```
 ** On entry to SGEMV  parameter number  6 had an illegal value
 ** On entry to SBGEMV  parameter number  6 had an illegal value
```

**Comment by ChipKerchner** [comment]
I believe this PR is ready for merging.

**Comment by ChipKerchner** [comment]
Actually zero length GEMV will not work because of this (and other checks)

```
if (lda < MAX(1, m))   info = 6;
```

If it is included, I get this

```
 ** On entry to SGEMV  parameter number  6 had an illegal value
 ** On entry to SBGEMV  parameter number  6 had an illegal value
```

**Comment by ChipKerchner** [comment]
So this PR is ready.  Sorry about all the changes.

**Comment by martin-frbg** [comment]
Thank you (sorry for causing extra work with what was just a spontaneous thought before going on a long drive)

**Pull request merged**
