### PR TITLE
Disable _TRMV parallelism at file top

### PR DESCRIPTION
**Pull request by brada4**
Restore old SMP code path
And use old UP path via single define

### CODE REVIEW

**Comment by martin-frbg** [comment]
This removes a FIXME without fixing anything except cosmetics ?

**Comment by brada4** [comment]
Sorry, lost in clipboard. Only intent is to avoid unnecessary thread calculation in complex case while FIXME hangs over it.

**Comment by martin-frbg** [comment]
Actually on revisiting that FIXME I am now certain that the proper fix is the same as #1389 - and it is totally unclear to me why I came to a different conclusion in #1332. So this is going to be superseded by #2026...

**Comment by brada4** [comment]
Perfect.

**Pull request closed without merging**
