### PR TITLE
Avoid calling DIRECT codepath in DYNAMIC_ARCH on non-SKX

### PR DESCRIPTION
**Pull request by martin-frbg**
#2526 (possibly #2524 as well)

### CODE REVIEW

**Comment by mattip** [comment]
One way to test this would be to add a x64 run on azure pipelines, which I think has non-SKX hardware (at least that is my operative assumption from the bug report).

**Comment by martin-frbg** [comment]
I have both kinds of hardware available locally, just need to get things organized as I need the SKX for other tasks as well.

**Comment by mattip** [comment]
one macOS test did not start

**Comment by martin-frbg** [comment]
Travis appears to have some ongoing problems with their MacOS hosts, I have been restarting CI jobs where necessary over the weekend. Still not sure if this PR is actually needed.

**Comment by mattip** [comment]
This is failing to buld in some configurations of MacPython/openblas-libs#28:
```
make DYNAMIC_ARCH=1 USE_OPENMP=0 NUM_THREADS=64 BINARY=64

gemm.c: In function ‘cblas_sgemm’:

gemm.c:276:19: error: ‘gotoblas_SKYLAKEX’ undeclared (first use in this function); did you mean ‘gotoblas_t’?

  if (gotoblas == &gotoblas_SKYLAKEX)

                   ^~~~~~~~~~~~~~~~~

                   gotoblas_t
```

**Comment by martin-frbg** [comment]
Thanks for the feedback. Could that be a configuration that does not have AVX512 ? Otherwise it is unclear to me why gotoblas_SKYLAKEX could be unknown.

**Comment by mattip** [comment]
apparently :) I am not sure how travis CI chooses what hardware for each option in the matrix

**Comment by martin-frbg** [comment]
Some pretty poor logic I put in there... this just won't be known at compile time unless the planets happen to be lined up correctly. I'll see if simply checking for core SKYLAKEX being defined does the trick.

**Comment by mattip** [comment]
No pressure. Please xref #2526 from the new PR so I can try it out.

**Comment by martin-frbg** [comment]
Probably makes more sense to expose the support_avx512 function that is already in dynamic.c and call that at runtime ... testing this now.

**Comment by leezu** [comment]
@martin-frbg is there any plan to release an OpenBLAS version including this fix shortly? If not, how about backporting the fix to 0.3.9 and releasing 0.3.9b?

Thank you!

**Comment by martin-frbg** [comment]
@leezu early June would certainly make sense (3 months since last release), not sure if I can make it happen next weekend. (Not in favor of doing "b" releases unless for a very bad bug that affects many/most platforms - otherwise there would have to be a microrelease every few days)

**Pull request merged**
