### PR TITLE
POWER: Fixing syntax error in makefile

### PR DESCRIPTION
**Pull request by RajalakshmiSR**
Fixing syntax issue in Makefile.power added by recent commit
af19cda65aef4d033ae33213013c88b0a99f9da2

### CODE REVIEW

**Comment by martin-frbg** [comment]
Aww, sorry for that.

**Comment by RajalakshmiSR** [comment]
Do you know how we can avoid these issues with our Travis CI  as we have POWER9 added in Travis. Ref : https://github.com/xianyi/OpenBLAS/issues/2754

**Comment by martin-frbg** [comment]
I do not think Travis (or actually OSUOSL providing the POWER9 hardware to them) is offering POWER10 yet. Perhaps I can set up qemu (POWER10 support appears to be very limited but may be enough to get a build started), but primarily I need to be more
careful with edits (or stop using github's simple web editor for good)

**Comment by RajalakshmiSR** [comment]
Yes we don’t have POWER10 yet in OSUOSL, but the question is about general POWER testing and not related to this issue/PR.
Do we have an active POWER build job?

**Comment by martin-frbg** [comment]
The one in Travis is active again since a few days (needed xianyi to initiate the migration to travis.com and apply for free credits). But it cannot catch bugs that I introduce in P10-specific sections of the Makefile.

**Comment by RajalakshmiSR** [comment]
Thanks @martin-frbg

**Pull request merged**
