### PR TITLE
Fix calculation of the non-exceptional shift values in LAPACK complex QZ

### PR DESCRIPTION
**Pull request by martin-frbg**
from the updated version of Reference-LAPACK PR 477, solving occasional (rare?) convergence failures in complex GGEV/GGES
Original issue is https://github.com/Reference-LAPACK/lapack/issues/475

### CODE REVIEW

**Comment by MigMuc** [comment]
There is a spelling mistake LSAME instead of LLSAME.

**Comment by pablosanjose** [comment]
> There is a spelling mistake LSAME instead of LLSAME.

Could somebody please confirm or refute this? I'm proposing this as a patch downstream (for Julia)

**Comment by martin-frbg** [comment]
Oh, right you are - seems gfortran is not visibly annoyed as it "only" affects the declaration as EXTERNAL.

**Comment by pablosanjose** [comment]
Thanks for the confirmation

**Pull request merged**
