### PR TITLE
Support compiling with clang on windows

### PR DESCRIPTION
**Pull request by isuruf**
In CMake, `MSVC` is set to `1` for `clang` when `clang` is targeting the `MSVC` runtime. So there were a few changes for that.

With clang, the assembly files can be compiled and therefore optimized kernel is enabled by default for clang on windows.

One issue I can't figure out is why `utest/openblas_utest.exe` gives the following
```
RESULTS: 0 tests (0 ok, 0 failed, 0 skipped)
```

Any ideas?

### CODE REVIEW

**Comment by brada4** [comment]
You change cmake+clang build on linux, you should not.

**Comment by isuruf** [comment]
@brada4, I don't think I have. Can you elaborate more?

**Comment by brada4** [comment]
I understood, you compile with clang in vcvarsall.bat environment. 
What do you intend to do for fortran part?

**Comment by martin-frbg** [comment]
Support for flang was added a few days ago, __if__ this is also available on windows it would seem a natural choice ?

**Comment by isuruf** [comment]
I haven't used flang on windows. They don't mention windows support.

**Comment by brada4** [comment]
No flang on Windows.
The problem is that using mingw gfortran for lapack pulls some 4-5 file extra redist dlls from mingw.
There is no problem with mingw blas-only build that links only to msvcrt.dll, so this PR just another way to achieve same. But a support for another compiler is always nice.
Quite a great job sanitizing Complex number support between the lines.

**Comment by brada4** [comment]
I just read what I wrote, i think gfortran unnecesarily has -lpthread in Windows build, I will check this theory tomorrow when I get to see Windows. Maybe one dll less if i am right

**Comment by martin-frbg** [comment]
I'm given to understand linking to mingw-built libraries is not always desirable in Windows projects due some kind of version conflict with/of CRT implementations ? In that case a non-mingw build that actually uses the optimized assembly kernels (unlike what you would currently get with VC, as that does not support inline assembly and AT&T-style assembly syntax) would probably be an improvement even if it is limited to (C)BLAS for now.
I take it that brada4' initial complaint was a misunderstanding, so that would leave your very own open question about the utest doing nothing - did this get fixed as part of your PR1259 ?

**Comment by isuruf** [comment]
No, it didn't get fixed. It has to do with some issue in ctest that it can't find the tests using ctest "magic"

**Comment by brada4** [comment]
I mistook vs clang with llvm installer, yes i am wrong,

**Comment by martin-frbg** [comment]
I'm not sure I even understand how ctest/utest is supposed to work. What I did notice is that ctest.h has
a few #ifdefs for various compilers that appear to influence its workings - perhaps a heavyhanded approach of just trying #define __CTEST_APPLE and #define __CTEST_MSVC in turn might uncover something ?

**Comment by brada4** [comment]
Actually mingw libraries are better than msvc built ones as they do not link to particular version of msvcrt
i.e prebuilt binary is significantly less consumable - only on same msvcrt - than mingw one, but integrating OpenBLAS in own project and building along rest against current msvcrt (with known limitation of absent flang and lapack) still could be option for many.

**Comment by isuruf** [comment]
I tried lots of ways to make ctest support clang on windows, but it can't find the tests automatically. So, I've added a file that adds the tests manually.

**Comment by isuruf** [comment]
Travis failure is unrelated.

**Comment by martin-frbg** [comment]
Yes, linker task got killed with SIGKILL - could be it hit the 4mb logfile limit from all the type conversion and uninitialized variable warnings (which are mostly "imported" with netlib lapack I think).

**Comment by martin-frbg** [comment]
Hmm. Actually the travis logfile for the killed job is a mere 194k in size. I am beginning to wonder if we are seeing fallout from #1255 here, or if it was just a coincidental instability of the travis host ?

**Comment by isuruf** [comment]
I've added instructions here, https://github.com/xianyi/OpenBLAS/wiki/How-to-use-OpenBLAS-in-Microsoft-Visual-Studio#3-cmake-and-clang-on-windows

**Comment by brada4** [comment]
Small clarification about limitations added, guide looks good.

**Pull request merged**
