### PR TITLE
Fix building with only a subset of variable types on Windows

### LINKED ISSUE #3779: Fails to build with only `BUILD_SINGLE` and `BUILD_DOUBLE` on Windows
Building OpenBLAS fails on Windows when enabling only single and double (`-DBUILD_SINGLE=ON -DBUILD_DOUBLE=ON`
```
[2868/5474] Building C object driver/others/CMakeFiles/driver_others.dir/blas_server_win32.c.obj
FAILED: driver/others/CMakeFiles/driver_others.dir/blas_server_win32.c.obj
D:\Programs\msys64_test\clang64\bin\clang.exe  -ID:/dev/MINGW-packages/mingw-w64-openblas/src/OpenBLAS-0.3.21 -ID:/dev/MINGW-packages/mingw-w64-openblas/src/build-CLANG64-32 -DHAVE_C11 -DMS_ABI -Wall -m64 -DSMALL_MATRIX_OPT -DDYNAMIC_ARCH -DSMP_SERVER -DMAX_CPU_NUMBER=64 -DMAX_PARALLEL_NUMBER=1 -DNO_AFFINITY -DVERSION="\"0.3.21\"" -DBUILD_SINGLE -DBUILD_DOUBLE -O3 -DNDEBUG -MD -MT driver/others/CMakeFiles/driver_others.dir/blas_server_win32.c.obj -MF driver\others\CMakeFiles\driver_others.dir\blas_server_win32.c.obj.d -o driver/others/CMakeFiles/driver_others.dir/blas_server_win32.c.obj -c D:/dev/MINGW-packages/mingw-w64-openblas/src/OpenBLAS-0.3.21/driver/others/blas_server_win32.c
D:/dev/MINGW-packages/mingw-w64-openblas/src/OpenBLAS-0.3.21/driver/others/blas_server_win32.c:298:40: error: use of undeclared identifier 'ZGEMM_P'
              sb = (void *)(((BLASLONG)sa + ((ZGEMM_P * ZGEMM_Q * 2 * sizeof(double)
                                              ^
D:/dev/MINGW-packages/mingw-w64-openblas/src/OpenBLAS-0.3.21/driver/others/blas_server_win32.c:298:50: error: use of undeclared identifier 'ZGEMM_Q'
              sb = (void *)(((BLASLONG)sa + ((ZGEMM_P * ZGEMM_Q * 2 * sizeof(double)
                                                        ^
D:/dev/MINGW-packages/mingw-w64-openblas/src/OpenBLAS-0.3.21/driver/others/blas_server_win32.c:301:40: error: use of undeclared identifier 'CGEMM_P'
              sb = (void *)(((BLASLONG)sa + ((CGEMM_P * CGEMM_Q * 2 * sizeof(float)
                                              ^
D:/dev/MINGW-packages/mingw-w64-openblas/src/OpenBLAS-0.3.21/driver/others/blas_server_win32.c:301:50: error: use of undeclared identifier 'CGEMM_Q'
              sb = (void *)(((BLASLONG)sa + ((CGEMM_P * CGEMM_Q * 2 * sizeof(float)
                                                        ^
D:/dev/MINGW-packages/mingw-w64-openblas/src/OpenBLAS-0.3.21/driver/others/blas_server_win32.c:567:30: warning: cast to 'void *' from smaller integer type 'long' [-Wint-to-void-pointer-cast]
                                     blas_thread_server, (void *)i,
                                                         ^~~~~~~~~
1 warning and 4 errors generated.
```

### PR DESCRIPTION
**Pull request by martin-frbg**
fixes #3779 (glaring omission in my #2852)

### CODE REVIEW

**Comment by MehdiChinoune** [comment]
still fails
```
[3884/7735] Building C object driver/others/CMakeFiles/driver_others.dir/blas_server_win32.c.obj
FAILED: driver/others/CMakeFiles/driver_others.dir/blas_server_win32.c.obj
D:\Programs\msys64_test\clang64\bin\clang.exe  -ID:/dev/MINGW-packages/mingw-w64-openblas/src/OpenBLAS-0.3.21 -ID:/dev/MINGW-packages/m
ingw-w64-openblas/src/build-CLANG64-32 -DHAVE_C11 -DMS_ABI -Wall -m64 -DSMALL_MATRIX_OPT -DDYNAMIC_ARCH -DSMP_SERVER -DMAX_CPU_NUMBER=6
4 -DMAX_PARALLEL_NUMBER=1 -DNO_AFFINITY -DVERSION="\"0.3.21\"" -DBUILD_SINGLE -DBUILD_DOUBLE -O3 -DNDEBUG -MD -MT driver/others/CMakeFi
les/driver_others.dir/blas_server_win32.c.obj -MF driver\others\CMakeFiles\driver_others.dir\blas_server_win32.c.obj.d -o driver/others
/CMakeFiles/driver_others.dir/blas_server_win32.c.obj -c D:/dev/MINGW-packages/mingw-w64-openblas/src/OpenBLAS-0.3.21/driver/others/bla
s_server_win32.c
D:/dev/MINGW-packages/mingw-w64-openblas/src/OpenBLAS-0.3.21/driver/others/blas_server_win32.c:298:40: error: use of undeclared identif
ier 'ZGEMM_P'
              sb = (void *)(((BLASLONG)sa + ((ZGEMM_P * ZGEMM_Q * 2 * sizeof(double)
                                              ^
D:/dev/MINGW-packages/mingw-w64-openblas/src/OpenBLAS-0.3.21/driver/others/blas_server_win32.c:298:50: error: use of undeclared identif
ier 'ZGEMM_Q'
              sb = (void *)(((BLASLONG)sa + ((ZGEMM_P * ZGEMM_Q * 2 * sizeof(double)
                                                        ^
D:/dev/MINGW-packages/mingw-w64-openblas/src/OpenBLAS-0.3.21/driver/others/blas_server_win32.c:301:40: error: use of undeclared identif
ier 'CGEMM_P'
              sb = (void *)(((BLASLONG)sa + ((CGEMM_P * CGEMM_Q * 2 * sizeof(float)
                                              ^
D:/dev/MINGW-packages/mingw-w64-openblas/src/OpenBLAS-0.3.21/driver/others/blas_server_win32.c:301:50: error: use of undeclared identif
ier 'CGEMM_Q'
              sb = (void *)(((BLASLONG)sa + ((CGEMM_P * CGEMM_Q * 2 * sizeof(float)
                                                        ^
D:/dev/MINGW-packages/mingw-w64-openblas/src/OpenBLAS-0.3.21/driver/others/blas_server_win32.c:567:30: warning: cast to 'void *' from s
maller integer type 'long' [-Wint-to-void-pointer-cast]
                                     blas_thread_server, (void *)i,
                                                         ^~~~~~~~~
1 warning and 4 errors generated.
```

**Comment by MehdiChinoune** [comment]
LAPACKE needs some work:
```
FAILED: lib/libopenblas.dll lib/libopenblas.dll.a
cmd.exe /C "cd . && D:\Programs\msys64_test\clang64\bin\flang-new.exe -flang-experimental-exec -Qunused-arguments   -shared -o lib\libo
penblas.dll -Wl,--out-implib,lib\libopenblas.dll.a -Wl,--major-image-version,0,--minor-image-version,3 @CMakeFiles\openblas_shared.rsp
 && cd ."
ld.lld: error: undefined symbol: __mth_i_ipowi
>>> referenced by D:/dev/MINGW-packages/mingw-w64-openblas/src/build-CLANG64-32/./CMakeFiles/LAPACK_OVERRIDES.dir/lapack-netlib/SRC/sge
lsd.f-pp.f:102
>>>               CMakeFiles/LAPACK_OVERRIDES.dir/lapack-netlib/SRC/sgelsd.f.obj:(sgelsd_)
>>> referenced by D:/dev/MINGW-packages/mingw-w64-openblas/src/build-CLANG64-32/./CMakeFiles/LAPACK_OVERRIDES.dir/lapack-netlib/SRC/sge
lsd.f-pp.f:108
>>>               CMakeFiles/LAPACK_OVERRIDES.dir/lapack-netlib/SRC/sgelsd.f.obj:(sgelsd_)
>>> referenced by D:/dev/MINGW-packages/mingw-w64-openblas/src/build-CLANG64-32/./CMakeFiles/LAPACK_OVERRIDES.dir/lapack-netlib/SRC/sla
qz0.f-pp.f:163
>>>               CMakeFiles/LAPACK_OVERRIDES.dir/lapack-netlib/SRC/slaqz0.f.obj:(slaqz0_)
>>> referenced 101 more times

ld.lld: error: undefined symbol: clatms_
>>> referenced by CMakeFiles/LAPACKE.dir/lapack-netlib/LAPACKE/src/lapacke_clatms_work.c.obj:(LAPACKE_clatms_work)
>>> referenced by CMakeFiles/LAPACKE.dir/lapack-netlib/LAPACKE/src/lapacke_clatms_work.c.obj:(LAPACKE_clatms_work)

ld.lld: error: undefined symbol: zlatms_
>>> referenced by CMakeFiles/LAPACKE.dir/lapack-netlib/LAPACKE/src/lapacke_zlatms_work.c.obj:(LAPACKE_zlatms_work)
>>> referenced by CMakeFiles/LAPACKE.dir/lapack-netlib/LAPACKE/src/lapacke_zlatms_work.c.obj:(LAPACKE_zlatms_work)

ld.lld: error: undefined symbol: clagge_
>>> referenced by CMakeFiles/LAPACKE.dir/lapack-netlib/LAPACKE/src/lapacke_clagge_work.c.obj:(LAPACKE_clagge_work)
>>> referenced by CMakeFiles/LAPACKE.dir/lapack-netlib/LAPACKE/src/lapacke_clagge_work.c.obj:(LAPACKE_clagge_work)

ld.lld: error: undefined symbol: zlagge_
>>> referenced by CMakeFiles/LAPACKE.dir/lapack-netlib/LAPACKE/src/lapacke_zlagge_work.c.obj:(LAPACKE_zlagge_work)
>>> referenced by CMakeFiles/LAPACKE.dir/lapack-netlib/LAPACKE/src/lapacke_zlagge_work.c.obj:(LAPACKE_zlagge_work)

ld.lld: error: undefined symbol: claghe_
>>> referenced by CMakeFiles/LAPACKE.dir/lapack-netlib/LAPACKE/src/lapacke_claghe_work.c.obj:(LAPACKE_claghe_work)
>>> referenced by CMakeFiles/LAPACKE.dir/lapack-netlib/LAPACKE/src/lapacke_claghe_work.c.obj:(LAPACKE_claghe_work)

ld.lld: error: undefined symbol: zlaghe_
>>> referenced by CMakeFiles/LAPACKE.dir/lapack-netlib/LAPACKE/src/lapacke_zlaghe_work.c.obj:(LAPACKE_zlaghe_work)
>>> referenced by CMakeFiles/LAPACKE.dir/lapack-netlib/LAPACKE/src/lapacke_zlaghe_work.c.obj:(LAPACKE_zlaghe_work)

ld.lld: error: undefined symbol: clagsy_
>>> referenced by CMakeFiles/LAPACKE.dir/lapack-netlib/LAPACKE/src/lapacke_clagsy_work.c.obj:(LAPACKE_clagsy_work)
>>> referenced by CMakeFiles/LAPACKE.dir/lapack-netlib/LAPACKE/src/lapacke_clagsy_work.c.obj:(LAPACKE_clagsy_work)

ld.lld: error: undefined symbol: zlagsy_
>>> referenced by CMakeFiles/LAPACKE.dir/lapack-netlib/LAPACKE/src/lapacke_zlagsy_work.c.obj:(LAPACKE_zlagsy_work)
>>> referenced by CMakeFiles/LAPACKE.dir/lapack-netlib/LAPACKE/src/lapacke_zlagsy_work.c.obj:(LAPACKE_zlagsy_work)
flang-new: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by martin-frbg** [comment]
can't reproduce that (on android/arm64 at least, but don't see why windows/x86 should be different in this regard)

**Comment by MehdiChinoune** [comment]
I will retry.

**Pull request merged**
