### PR TITLE
[WIP] Use latest GCC for some Travis builds

### PR DESCRIPTION
**Pull request by marxin**

### CODE REVIEW

**Comment by martin-frbg** [comment]
I am not convinced that we would want to convert all CI jobs to only the latest and greatest when there are many users stuck with whatever their distribution came with ? (Non-priviledged users on centrally managed systems with older RHEL for example)  
Looks like the travis failures are precisely because there is no readily available gcc-9 for those environments

**Comment by marxin** [comment]
> I am not convinced that we would want to convert all CI jobs to only the latest and greatest when there are many users stuck with whatever their distribution came with ? (Non-priviledged users on centrally managed systems with older RHEL for example)

I would at least mix it. Some build target can be run with `gcc9`. Note that `gcc (Ubuntu/Linaro 4.6.3-1ubuntu5) 4.6.3` is out of our official GCC support for about 6 years.

> Looks like the travis failures are precisely because there is no readily available gcc-9 for those environments

Should be possible, I enabled that for godot travis builds:
https://travis-ci.org/godotengine/godot/jobs/652854893?utm_medium=notification&utm_source=github_status

**Comment by martin-frbg** [comment]
I'd convert some or add one with gcc-9 but leave some old ones no matter how outdated they may be from a maintainer perspective. One just can't magically upgrade all the systems out there..

**Comment by marxin** [comment]
It works for me!

**Comment by marxin** [comment]
With latest GCC we have problem with legacy binutils:
```
gcc-9 -c -O2 -DMAX_STACK_ALLOC=2048 -Wall -m64 -DF_INTERFACE_GFORT -fPIC -DDYNAMIC_ARCH -DSMP_SERVER -DNO_WARMUP -DMAX_CPU_NUMBER=32 -DMAX_PARALLEL_NUMBER=1 -DVERSION=\"0.3.9.dev\" -DASMNAME=sdot_k_SKYLAKEX -DASMFNAME=sdot_k_SKYLAKEX_ -DNAME=sdot_k_SKYLAKEX_ -DCNAME=sdot_k_SKYLAKEX -DCHAR_NAME=\"sdot_k_SKYLAKEX_\" -DCHAR_CNAME=\"sdot_k_SKYLAKEX\" -DNO_AFFINITY -DTS=_SKYLAKEX -I.. -DBUILD_KERNEL -DTABLE_NAME=gotoblas_SKYLAKEX -march=skylake-avx512 -UDOUBLE  -UCOMPLEX -UCOMPLEX -UDOUBLE ../kernel/x86_64/sdot.c -o sdot_k_SKYLAKEX.o
/tmp/ccA39DvV.s: Assembler messages:
/tmp/ccA39DvV.s:137: Error: bad register name `%zmm2'
/tmp/ccA39DvV.s:150: Error: bad register name `%zmm3'
/tmp/ccA39DvV.s:152: Error: bad register name `%zmm2'
/tmp/ccA39DvV.s:154: Error: bad register name `%zmm3'
/tmp/ccA39DvV.s:155: Error: bad register name `%zmm3'
/tmp/ccA39DvV.s:156: Error: bad register name `%zmm2'
/tmp/ccA39DvV.s:157: Error: bad register name `%zmm3'
/tmp/ccA39DvV.s:158: Error: bad register name `%zmm3'
/tmp/ccA39DvV.s:159: Error: bad register name `%zmm2'
/tmp/ccA39DvV.s:160: Error: bad register name `%zmm3'
/tmp/ccA39DvV.s:161: Error: bad register name `%zmm3'
/tmp/ccA39DvV.s:162: Error: bad register name `%zmm2'
/tmp/ccA39DvV.s:163: Error: bad register name `%zmm3'
make[1]: *** [saxpy_k_SKYLAKEX.o] Error 1
make[1]: *** Waiting for unfinished jobs....
/tmp/ccVRgREX.s: Assembler messages:
/tmp/ccVRgREX.s:136: Error: bad register name `%zmm2'
/tmp/ccVRgREX.s:137: Error: bad register name `%zmm2'
/tmp/ccVRgREX.s:138: Error: bad register name `%zmm2'
/tmp/ccVRgREX.s:142: Error: bad register name `%zmm6'
/tmp/ccVRgREX.s:143: Error: bad register name `%zmm7'
/tmp/ccVRgREX.s:144: Error: bad register name `%zmm6'
/tmp/ccVRgREX.s:145: Error: bad register name `%zmm7'
/tmp/ccVRgREX.s:146: Error: bad register name `%zmm6'
/tmp/ccVRgREX.s:147: Error: bad register name `%zmm7'
/tmp/ccVRgREX.s:149: Error: bad register name `%zmm6'
/tmp/ccVRgREX.s:150: Error: bad register name `%zmm7'
/tmp/ccVRgREX.s:155: Error: no such instruction: `vextractf32x8 $0x1,%zmm1,%ymm1'
/tmp/ccVRgREX.s:159: Error: no such instruction: `vextractf32x8 $0x1,%zmm4,%ymm4'
/tmp/ccVRgREX.s:163: Error: no such instruction: `vextractf32x8 $0x1,%zmm3,%ymm3'
/tmp/ccVRgREX.s:167: Error: no such instruction: `vextractf32x8 $0x1,%zmm2,%ymm2'
```

**Comment by martin-frbg** [comment]
I wonder why the avx512 compile test in c_check did not catch this ? (OTOH a user who upgrades from an ancient gcc without also updating binutils is probably asking for trouble anyway)

**Comment by marxin** [comment]
It comes from a C compiled file:
```
./kernel/x86_64/sdot_microk_skylakex-2.c
```

It's may use a AVX512 subset that is not yet supported by Travis binutils.
I'm probably bailing out the `gcc-9` usage for now..

**Pull request closed without merging**
