### PR TITLE
(sgemm) Apply some of the SKYLAKEX optimizations also to HASWELL

### PR DESCRIPTION
**Pull request by fenrus75**
For small matrices there's some interesting-enough wins to be had:

 M   | N    | K    | cycles        | improvement
-----|------|------|---------------|------------
   1 |    1 |    1 |        269.6  |  -4.5% |
   2 |    2 |    2 |        287.7  |  -0.5% |
   3 |    3 |    3 |        397.6  |   1.0% |
   4 |    4 |    4 |        306.4  |   1.2x |
   6 |    6 |    6 |        577.0  |   1.1x |
   8 |    8 |    8 |        414.0  |   1.3x |
  16 |   16 |   16 |       1030.3  |   1.4x |
  32 |   32 |   32 |       4573.9  |   1.8x |
  48 |   48 |   48 |      12216.6  |   1.4x |
  64 |   64 |   64 |      26284.3  |   1.5x |
  96 |   96 |   96 |      76087.1  |   1.4x |
 128 |  128 |  128 |     170823.4  |   1.3x |
 192 |  192 |  192 |     541464.6  |   1.2x |
 256 |  256 |  256 |    1238842.0  |   1.2x |
 512 |  512 |  512 |    9501534.7  |   8.3% |
1024 | 1024 | 1024 |   78758387.0  |   2.3% |
   4 |   16 |    9 |        379.7  |   1.3x |
  64 |  128 |  192 |     132797.8  |   1.2x |
  37 |   81 |  193 |      63104.2  |   1.2x |
 512 |  412 |  800 |   12500033.8  |   7.2% |
 256 |    1 |  256 |     110118.4  |   2.1x |
 256 |    2 |  256 |     133074.0  |   1.9x |
 256 |    4 |  256 |     111973.9  |   2.0x |
 256 |    8 |  256 |     113988.2  |   2.0x |
 256 |   16 |  256 |     139785.1  |   1.9x |
 256 |   32 |  256 |     213030.3  |   1.6x |
 256 |   64 |  256 |     359315.7  |   1.4x |
   1 |  256 |  256 |      64398.3  |   3.4% |
   2 |  256 |  256 |      68050.3  |   2.2% |
   4 |  256 |  256 |      68803.7  |   4.7% |
   8 |  256 |  256 |      88886.5  |   5.6% |
  16 |  256 |  256 |     123633.7  |   6.8% |
  32 |  256 |  256 |     199070.4  |   9.8% |
  64 |  256 |  256 |     345128.9  |   1.1x |
 256 |  256 |    1 |      45093.0  |   2.3x |
 256 |  256 |    2 |      50227.3  |   2.2x |
 256 |  256 |    4 |      60993.9  |   1.9x |
 256 |  256 |    8 |      82554.1  |   1.7x |
 256 |  256 |   16 |     123221.1  |   1.5x |
 256 |  256 |   32 |     200263.4  |   1.4x |
 256 |  256 |   64 |     341454.0  |   1.3x |
  35 | 8457 | 1760 |   61871520.9  |  -0.4% |

### CODE REVIEW

**Comment by fenrus75** [comment]
hmm seems clang wants -march=haswell for the gemm kernel. will poke at this

**Comment by martin-frbg** [comment]
See skylakex additions in Makefile.x86_64 (non-dynamic) and kernel/Makefile (dynamic_arch case). Also cmake/system.cmake for the cmake builds (have not gotten around to checking if this "pollutes" the dynamic_arch builds with host-specific arch optimizations like gmake builds did before #1910)

**Comment by martin-frbg** [comment]
Seems neither -mavx2 nor -march=core-avx2 is supported on gcc before 4.7.0 (some of the travis setups use 4.6.3)

**Comment by fenrus75** [comment]
we can do a not so nice hack and include the generic one if __AVX2__ is not
defined...... if you're on an old gcc you won't get the performance but at
least it'll compile

**Comment by martin-frbg** [comment]
I assume by "the generic one" you mean the current code without this optimization ? For clang it seems support was added somewhere around 3.2, so this should only affect systems older than about 6 or 7 years.

**Comment by fenrus75** [comment]
the new patch should make the code compile with and without avx2.

**Pull request merged**
