### PR TITLE
Move ARMv8/gcc CI job from Travis to Azure

### PR DESCRIPTION
**Pull request by martin-frbg**

### CODE REVIEW

**Comment by tylerjereddy** [comment]
Looks great -- another 50 minutes out of the Travis burden!

Hopefully we get Shippable CI at some point for native ARMv8, which I suspect would be faster / more suitable in the long term.

**Comment by isuruf** [comment]
@tylerjereddy, have you looked at drone.io for arm? It has parallel builds for open source projects. (conda-forge will be using drone.io instead of shippable in the near future)

**Comment by tylerjereddy** [comment]
@isuruf Oh cool! Never heard of it--no problems with GitHub integration / hours per month?

**Comment by isuruf** [comment]
@tylerjereddy, works fine with github integration. No hours per month. 96 core native hardware.

**Comment by martin-frbg** [comment]
I find the documentation at drone.io a bit confusing - while they do mention providing a free cloud service for opensource projects, the documentation appears to be all about setting up their CI framework on local hardware.

**Comment by martin-frbg** [comment]
BTW the ARM/clang jobs timed out on Azure as well, so not much point in moving them.

**Pull request merged**
