### PR TITLE
Reword/expand comments in Makefile.rule

### PR DESCRIPTION
**Pull request by TiborGY**
Lots of small changes in the wording of the comments, plus an expansion of the NUM_THREADS and NO_AFFINITY sections.

### CODE REVIEW

**Comment by martin-frbg** [comment]
I think the part about not wanting to _install_ the static library is technically correct, as the gmake  build proceeds via libopenblas.a in any case.
(And if you want to expand the NO_AFFINITY section it might make sense to spell out what the typical incompatibility is - any subsequent threads of the "other" program end up locked to the same core(s) as OpenBLAS )

**Review by brada4 — CHANGES_REQUESTED** [review]
Your num_threads description states all redistributed packages configured with 32/64/128 threads are wrong.
Why generic fortran option os atributed to ifort? 
Affinity is off by default and only affines threads to cores, nothing with memory. One certain application is numpy.

**Comment by TiborGY** [comment]
> Your num_threads description states all redistributed packages configured with 32/64/128 threads are wrong.

Well, the old description was even worse, suggesting less threads than the number of cores. But I can add a note for package maintainers.
> Why generic fortran option os atributed to ifort?

GCC does not recognize "-i8" at all, the option that turns on 64-bit integers is "-fdefault-integer-8".
> Affinity is off by default and only affines threads to cores, nothing with memory. One certain application is numpy.

OK, I will fix this, I was following the old description, and that stated "CPU/memory affinity". I assumed the old description was not wrong.

**Comment by martin-frbg** [comment]
I suspect the original wording as "Basically should be less than actual number of cores"  was meant in the sense of "you will want to define this only if you want less than what the autodetection would find anyway".
(This and most other comments are unchanged from GotoBLAS by Kazushige Goto. Apart from the slight language issues he probably did not foresee people building his library for redistribution rather than direct compilation on the target system. So allowing more threads than cpus _seen on the build host_ was probably not a plausible scenario back then.)

I'm perfectly OK with labeling the "-i8" option in the comment as ifort dialect for clarity.

Lastly calling it "CPU/memory" affinity probably makes sense  where memory access is not quite uniform e.g. between cores on separate dies. (Again the wording is Goto's, and I think he would have known)

**Comment by brada4** [comment]
Probably worth saying that NUM_THREADS is maximum and can be reduced at runtime if needed (with some examples)
And the proposed edit said that affinity is on by default. It is actually off to play safe with others.

**Comment by TiborGY** [comment]
> And the proposed edit said that affinity is on by default. It is actually off to play safe with others.

"For this reason, affinity handling is disabled by default." I cannot see how I could have made it clearer that it is **disabled by default**

**Comment by TiborGY** [comment]
I think if there are no further objections, this is ready to go.

**Comment by brada4** [comment]
The thing is num_threads sizes memory buffers, and larger than CPUs value is desirable if using threading outside OpenBLAS. Accurate reference to OPENBLAS_NUM_THREADS would help there.

**Comment by TiborGY** [comment]
> 
> 
> The thing is num_threads sizes memory buffers, and larger than CPUs value is desirable if using threading outside OpenBLAS.

AFAIK the current codebase always creates enough memory buffers for at least 50 threads.
> 
> 
> Accurate reference to OPENBLAS_NUM_THREADS would help there.

I refrained from mentioning that environment variable on purpose. There are many ways to set the actual number of used threads at runtime, and that is already documented elsewhere. I feel like mentioning only one of the possible ways could be misleading.

**Comment by brada4** [comment]
NUM_THREADS - Better to make a shortcut, current documentation could wish better structuring.

**Comment by martin-frbg** [comment]
Actually I think the new wording is quite adequate as it is now (minor nit: you retained a "the the" from the previous version in line 75). We may eventually want to move the lengthier descriptions to some new document named "OPTIONS" or the like, or rework the original `GotoBLAS_*` files.

**Pull request merged**
