### PR TITLE
(Much) Better support for MSVC/Windows in CMake (v0.2.x)

### LINKED ISSUE #1975: Static libs for MSVC prevented in cmakelists?
Hi!

I'm trying to understand why this line exists:
https://github.com/xianyi/OpenBLAS/blob/develop/CMakeLists.txt#L154

And can't figure it out. Why prevent static lib compilation on MSVC specifically?

### PR DESCRIPTION
**Pull request by danielgindi**
This closes #1975

### CODE REVIEW

**Comment by isuruf** [comment]
Looks good to me. (except for the indentation issues)

**Comment by martin-frbg** [comment]
My only problem with this is that I do not see any point in applying any patches to the stale, outdated 0.2.20 from two years ago.

**Comment by isuruf** [comment]
Right. I checked and most of this is in develop.

**Comment by danielgindi** [comment]
Yes, the 0.3 branch had a separate PR. This is for people who (for compatibility reasons) still use the 0.2 and this makes it easier to do MSVC compilation without patches and hacks.

**Pull request closed without merging**
