### PR TITLE
remove certain duplicate #include-s

### PR DESCRIPTION
**Pull request by brada4**
Only pertaining stdio math stdlib string headers.
Should any problem arise it can be compensated from common.h

### CODE REVIEW

**Comment by martin-frbg** [comment]
Probably needs rearranging the other `#include`s so that they come after common.h in case any of them depend on one of the headers this removes (on any of the supported platforms). 
Not sure this is worth it anyhow - changing over 500 files just to make them prettier ?

**Comment by brada4** [comment]
I knew you will be looking at 
```
bench.../....c:

#ifdef __CYGWIN32__
#include <sys/time.h>
```

That can be removed to as sys/time.h is included unconditionally in common.h 
Ths is just braindead grunt work part. There is some intelligence involved in cleaning other.

**Comment by brada4** [comment]
In principle it should become
```
#include "common.h"
#include <extra_system.h>
#include "uncomon.h"
```

**Comment by brada4** [comment]
I will split the patch into parts that have just single surplus file (like 400) then pay more attn to multiple , carefully sorting with common.h firss firstly.

**Pull request closed without merging**
