### PR TITLE
Remove redundant code

### PR DESCRIPTION
**Pull request by jijiwawa**
Remove redundant code in the benchmark directory

### CODE REVIEW

**Comment by martin-frbg** [comment]
That one supersedes #2487, right ? Pity I only realized this after deconflicting the older one. Need to check now that merging this would not throw out code from the others I guess...

**Comment by martin-frbg** [comment]
It would probably be easier if you could just resubmit this based on the current develop and with only the redundant code removed.

**Comment by jijiwawa** [comment]
> That one supersedes #2487, right ? 
yes

**Comment by jijiwawa** [comment]
> It would probably be easier if you could just resubmit this based on the current develop and with only the redundant code removed.

Resubmit done

**Comment by jijiwawa** [comment]
> That one supersedes #2487, right ? 

yes

**Comment by martin-frbg** [comment]
Thank you.

**Pull request merged**
