### PR TITLE
Update dgemm_kernel_4x8_haswell.S for reducing cache misses

### PR DESCRIPTION
**Pull request by wjc404**
Add some prefetch codes to reduce cache misses.

Improvement on i9-9900K: 0.6 GFLOPS for 1 thread, 8 GFLOPS for 8 threads.

Improvement on r7-3700X: 0.2 GFLOPS for 1 thread (TARGET=HASWELL).

By the way, where can I see the definitions of GEMM_P and GEMM_Q for a specific architecture? Thanks.

### CODE REVIEW

**Comment by martin-frbg** [comment]
GEMM_P and GEMM_Q are taken from the respective DGEMM_DEFAULT_(P or Q) in param.h - e.g. for 64bit Haswell DGEMM_P is 512 while DGEMM_Q on non-Windows platforms is 256 (128 when WINDOWS_API is defined). Unfortunately there is little documentation apart from K.Goto's seminal paper on the GEMM algorithm - apparently once one has mastered this code, it becomes trivially obvious (or the enlightened vanishes into some higher zen state).

**Comment by wjc404** [comment]
Screenshot from 2019-07-20 18-20-19
currently 98% MKL performance (i9-9900K, 8threads, 4.1GHz)

**Comment by wjc404** [comment]
gained another 0.4 GFLOPS

**Comment by wjc404** [comment]
2 dgemm tests of the newly-built OpenBLAS against Intel MKL(2018): m=10206, n=9573, k=10716, transa=N, transb=N, i9-9900K, avx-offset=6

Screenshot from 2019-07-20 23-13-20
(OMP_NUM_THREADS=2)

Screenshot from 2019-07-20 23-13-26
(OMP_NUM_THREADS=4)

**Comment by wjc404** [comment]
In summary, 1-thread performance on 9900K increased by 1GFLOPS after this update, 8-thread performance increased by ~10GFLOPS.

**Comment by martin-frbg** [comment]
Great, thanks a lot for this.

**Pull request merged**
