### PR TITLE
Fix DYNAMIC_ARCH builds with CMAKE on OSX and add corresponding test to Azure CI

### LINKED ISSUE #3408: Error: Build fail when linking OpenBLAS shared library with gfortran on macOS
Hi,
I am building OpenBLAS on macOS with gfortran and have an issue on the last step, when trying to link the final libopenblas.dylib shared library.

I am using the following OpenBLAS specific CMake configuration, on an x64 architecture:
`-DBUILD_WITHOUT_LAPACK=OFF -DBUILD_WITHOUT_CBLAS=OFF -DNOFORTRAN=OFF -DDYNAMIC_ARCH=ON -DDYNAMIC_OLDER=ON`

It is compiling all the 20000+ files correctly, then, there is the last step where I get:
`> collect2: fatal error: execvp: Argument list too long`

On the official FAQ, it is stated that we should take care of using response files thanks to the undocumented CMake variables: https://github.com/xianyi/OpenBLAS/wiki/Faq#cmakeosx-build-fails-with-argument-list-too-long
By the way, when using Ninja, there is also the `CMAKE_NINJA_FORCE_RESPONSE_FILE` variable.

I have the same behavior either if I am asking explicitly the response file or letting the default behavior: A response file is generated and used.
However, it seems the issue is more when gfortran itself is calling `collect2` to link through an `exec()` function.
I am seeing a similar issue reported 5 years ago by Brad King where he is explaining that it looks like a gfortran internal issue: https://gitlab.kitware.com/cmake/cmake/-/issues/16206#note_141137

Knowing these fact, I tried several things to have a successful build.

Firstly, regarding the `Argument list too long` itself, I can confirm the issue by checking if the `ARG_MAX` is reached
```
getconf ARG_MAX
> 1048576
wc -c CMakeFiles/openblas.rsp
> 1281606 CMakeFiles/openblas.rsp
```

Then, some tests to obtain the correct `libopenblas.dylib`.

Default CMake behavior:
```
gfortran <args...> @CMakeFiles/openblas.rsp
> collect2: fatal error: execvp: Argument list too long
```

Trying to forward directly to the linker as a response file
```
gfortran <args...> -Wl,@CMakeFiles/openblas.rsp
> gfortran: fatal error: no input files; unwilling to write output files
```

Trying to bypass the `no input files` error by using a dummy object
```
echo "" | gfortran -o dummy.o -c -x f95-cpp-input - # Awesome command to generate an empty dummy.o file
gfortran <args...> -Wl,@CMakeFiles/openblas.rsp dummy.o
> collect2: fatal error: execvp: Argument list too long
```

Generating a temporary archive with all objects and bypassing the `no input files` error
```
cat CMakeFiles/openblas.rsp | xargs -n1024 ar -ur libopenblas.a # Iteratively fill libopenblas.a with objects
echo "" | gfortran -o dummy.o -c -x f95-cpp-input -
gfortran <args...> -Wl,-force_load,libopenblas.a dummy.o
> SUCCESS
```

FYI I also tried to rebuild gfortran myself, but am here using the Homebrew version.

In the end, I am able to get a dynamic library of OpenBLAS through manual hacks but have several questions:
- Is it a known issue to have this kind of errors even when using response files?
- Do you see a simpler solution? Maybe I am missing something as it seems me an overly complicated process for such a standard thing
- I know it looks like more a gfortran (or CMake) oriented issue but it seems that, if confirmed, this issue has always been there. So, could it be something handled in `CMakeLists.txt`? I will try on my side to see if it is possible to have a proper handling of this issue but maybe I could then do a PR if it feels it could be useful.  As an example, here is a quite similar issue on `libflame` with a patch on the build process (not CMake): https://github.com/flame/libflame/issues/29

### PR DESCRIPTION
**Pull request by martin-frbg**
fixes #3408 using jbouny's suggestion

### CODE REVIEW

**Comment by isuruf** [comment]
@martin-frbg, what problem are you trying to solve here? Maybe I can help.

**Comment by martin-frbg** [comment]
@isuruf #3408 (cmake hitting the ARG_MAX on OSX when creating a DYNAMIC_ARCH library). I _think_ I have got the hack suggested in the issue ticket converted into cmake syntax, I am just fumbling around to get the correct (cmake variable for the) library name into the custom linker command now.

**Comment by isuruf** [comment]
Ah, thanks for the pointer. How about we build the shared library using the static library instead of object files and force the user to have build the static library on macOS with gcc compiler?

**Comment by martin-frbg** [comment]
Not sure that is a "legal" or desirable way of doing it. Anyway the response file mechanism seems to work, the unsolved part is just that the library name does not appear to have been built (by system.cmake) at the time the custom linker command is executed (or more likely it is not accessible in that context).

**Pull request merged**
