### PR TITLE
Add in runtime CPU detection for POWER.

### PR DESCRIPTION
**Pull request by RashmicaG**

### CODE REVIEW

**Comment by brada4** [comment]
There is still ton of other CPUs in Power series starting around MAC G5...

**Comment by martin-frbg** [comment]
@brada4 do you actually expect anybody to be using a 10+ years old PowerMac **and**  wanting DYNAMIC_ARCH to work on it ?

**Comment by brada4** [comment]
Actuallu power6 is discontinued by manufacturer days ago....
Looking at debian just 8 and 9 is worth now....

**Comment by martin-frbg** [comment]
Guess power6 still makes sense as a safe generlc fallback (more so than ppc970 or earlier) - at least I expect Rashmica will know better than eiher of us)

**Pull request merged**
