### PR TITLE
arm64: add the missing d9 register to the clobber list

### PR DESCRIPTION
**Pull request by ggouaillardet**
Refs. numpy/numpy#18422

Signed-off-by: Gilles Gouaillardet <gilles@rist.or.jp>

### CODE REVIEW

**Comment by mattip** [comment]
I think I am hitting this when using v0.3.15. Will there be a bug-fix release?

**Comment by martin-frbg** [comment]
I'm planning on releasing 0.3.16 soon (though not specifically for this bug, and no guarantee there won't be new ones)

**Comment by h-vetinari** [comment]
> I'm planning on releasing 0.3.16 soon (though not specifically for this bug, and no guarantee there won't be new ones)

Hey @martin-frbg, no rush, just checking where things stand on this, because I'm planning to update the blas versions across conda-forge very soon, and was wondering whether it makes sense for me to wait a day or so, if the release is really close.

**Comment by martin-frbg** [comment]
This weekend if I can make it

**Comment by mattip** [comment]
Thanks and good luck

**Pull request merged**
