### PR TITLE
zarch: treat z15 as z14 instead of generic

### PR DESCRIPTION
**Pull request by sharkcz**

### CODE REVIEW

**Comment by martin-frbg** [comment]
Thanks

**Comment by martin-frbg** [comment]
BTW I added cpuid 8562 for the smaller model on top of your patch.

**Comment by sharkcz** [comment]
> BTW I added cpuid 8562 for the smaller model on top of your patch.

sure, I missed that it has been announced too

**Comment by martin-frbg** [comment]
I stumbled on an older QEMU patch thread where both numbers were revealed by someone with an ibm.com address. (Amusingly this triggered a discussion as the official marketing name had not been revealed at the time, or perhaps not even decided on)

**Pull request merged**
