### PR TITLE
fix cblas_?gemmt

### PR DESCRIPTION
**Pull request by martin-frbg**

### CODE REVIEW

**Comment by BrannonKing** [comment]
Is this related to this issue? https://github.com/coin-or/Ipopt/issues/665

**Comment by mmuetzel** [comment]
IIUC, this PR fixes a bug that was introduced in #4006.
That was pushed *after* the release of OpenBLAS 0.2.23. So unless you are using a version from the development branch, you are not affected by the bug fixed in the PR.

**Comment by martin-frbg** [comment]
could be - I was not aware of that issue but gemmt in 0.3.23 happened to be fairly "limited in functionality" as the wrong source file got committed (see #4006 for that fix)

**Comment by mmuetzel** [comment]
Fwiw, your changes look good to me.

**Pull request merged**
