### PR TITLE
CMake: Use the correct library name on windows

### PR DESCRIPTION
**Pull request by ghost**
FindBLAS and FindLAPACK don't correctly detect the OpenBLAS library name on windows. I am unsure why this was originally set this way, but it has caused me some trouble.

Note that vcpkg patches this to remove its effects.

### CODE REVIEW

**Comment by martin-frbg** [comment]
Is this a general problem, or peculiar to vcpkg ? 
I notice that vcpkg has some of its packages named _libpackagename_ , while others including openblas are just _packagename_ , does this perhaps create problems where other vcpkg packages or tools are looking for openblas.dll instead of libopenblas.dll ? Or does the Windows cmake build leads to something really silly like liblibopenblas.dll in certain situations ?

**Comment by ghost** [comment]
The problem is that FindLAPACK and FindBLAS (from CMake) don't work if the library name is 'libopenblas' on Windows. It is not a general problem, but rather a problem that is specific to each Find* module that CMake defines.

**Comment by brada4** [comment]
Indeed almost nobody prepends library name with lib on windows. I wonder if "make" should not be changed this way to generate directly consumable module too.

**Comment by martin-frbg** [comment]
Thanks, I had not realized that FindLAPACK and FindBLAS are CMake modules. I intend to merge this if we do not get a reaction from xianyi soon.

**Pull request merged**
