### PR TITLE
Create OpenBLASConfig.cmake in cmake builds as well

### PR DESCRIPTION
**Pull request by martin-frbg**
Patch provided by loriab in #1529

### CODE REVIEW

**Comment by xsacha** [comment]
Thanks,
Will be good to see this in the next version.
I did the same thing here:
https://github.com/hunter-packages/OpenBLAS/commit/cfbd3563dbd1fa8f41f1547d6f642cee33e533e9
One thing I noticed after doing this is that the install path was not pushed to the Config
I needed to add this in a separate commit here:
https://github.com/hunter-packages/OpenBLAS/commit/fd4832ba3d74e67ad2adbf004e9603bea27c8892

**Comment by martin-frbg** [comment]
Thanks. Unfortunately I am not sure how to address this, as your version seems to be quite different from loriab's and I am not sure what to look for in the resulting config file. His version of the cmake.in seems to be much more elaborate than yours, so perhaps this supplies the required information ?

**Comment by xsacha** [comment]
Yes, this version is fine. It adds some things I didn't such as versioning.
Include path usually doesn't matter if you install to system.

**Comment by martin-frbg** [comment]
Thanks again for the review.

**Pull request merged**
