### PR TITLE
WIP: Support for Flang on Windows

### PR DESCRIPTION
**Pull request by insertinterestingnamehere**
This adds support for using flang on Windows. It appears @xoviat beat me to it, but I figured I'd post what got everything building for me for reference as well.

Things that still need to be addressed:

 - [x] Verify that none of these changes break anything when building with gfortran in CMake
 - [x] Check that the TIMER variable is chosen correctly for flang
 - [x] Verify that all the desired routines are actually exported from the compiled dll.

### CODE REVIEW

**Comment by ghost** [comment]
Sorry. I guess I was a little too eager.

**Comment by insertinterestingnamehere** [comment]
That or I was a little too slow. No worries.

**Comment by ghost** [comment]
Pending insertinterestingnamehere/OpenBLAS#1.

**Comment by insertinterestingnamehere** [comment]
Quick word on how I arrived at the lists of routines present in the CMake files for lapack and lapacke: I copied over the file lists from the more recent vendored copy of LAPACK in the repo and then adapted them by removing multiply defined symbols that conflicted with existing C files found elsewhere in the repo and adding the source files for any missing symbols (like the matgen routines).

**Comment by insertinterestingnamehere** [comment]
Appears to work fine with gfortran/gcc 7.2 from MinGW-w64. That build includes more tests by default than the current clang-cl/flang build though.

**Comment by ghost** [comment]
Looks like we have some problems. I would recommend b0afe10.

**Comment by insertinterestingnamehere** [comment]
cherry-picked. Thanks. It's odd that that wasn't needed on my local machine.

**Comment by isuruf** [comment]
@insertinterestingnamehere, can you remove the last commit and add https://github.com/isuruf/OpenBLAS/commit/98c317c579f355b7b5de2ff7a0f56e54b9b65a06 ?

You wouldn't have seen this locally because you probably were running cmake from a build directory and  the gensymbol script mistakenly assumes that the current working directory is the script directory.

**Comment by insertinterestingnamehere** [comment]
Sorry for the delay there. I've cherry picked that one instead.

**Comment by insertinterestingnamehere** [comment]
Yep, I've been running it from a separate build directory. That explains it.

**Comment by martin-frbg** [comment]
Isn't creating a separate build directory generally recommended by cmake or projects that use it ? (A change that allows either kind of builds to work is still good in my opinion)

**Comment by isuruf** [comment]
> Isn't creating a separate build directory generally recommended by cmake or projects that use it ?

yes, it is recommended. Some projects explicitly disable building in tree. I'm okay with either.

**Comment by insertinterestingnamehere** [comment]
Alright, I just checked that the correct TIMER setting is NONE. It is. At least for the time being, etime is not provided by flang. Since @isuruf already handled the code to make sure all the correct symbols are exported, this should be done now.

**Comment by isuruf** [comment]
@insertinterestingnamehere, can you also check that exports/gensymbol is not outdated?

**Comment by insertinterestingnamehere** [comment]
Sure, you mean that it exports symbols consistent with LAPACK 3.7?

**Comment by isuruf** [comment]
Yes. some symbols might be missing there.

**Comment by insertinterestingnamehere** [comment]
Okay, 3.7.0 support appears to have been added in https://github.com/insertinterestingnamehere/OpenBLAS/commit/a836fe8ec1250019d474b8dea12503b8b5ed5eae. The list added there is a superset of the routines listed as new in the 3.7.0 release notes (probably because auxiliary routines aren't mentioned in the release notes). Not all the routines mentioned in the release notes have their corresponding LAPACKE wrappers included for some reason (e.g. `lapacke_cgelq`).

**Comment by martin-frbg** [comment]
Omission of LAPACKE_cgelq &friends was actually an oversight in netlib 3.7.0 as well, see https://github.com/Reference-LAPACK/lapack/pull/118 . I _think_ I copied that PR as part of  #1095, but in any case it seems I never thought to check gensymbol.

**Comment by insertinterestingnamehere** [comment]
Got it, so for LAPACKE, we need to add `*geqr`, `*gelq`, `*gemlq`. Thanks. That limits the searching I need to do pretty considerably. I'll go ahead and add that here.

**Comment by insertinterestingnamehere** [comment]
Okay, I believe that should fix it. Builds all still pending.
Note: in this PR, I got the updated lapack.cmake by copying lists of source files from the netlib version and then removing files corresponding to multiply defined symbols. Do you remember if there were any missing fortran routines there that I'd need to add back in?

**Comment by martin-frbg** [comment]
I do not remember, but any multiply defined symbols can only come from the small set of functions reimplemented in "lapack" (as opposed to "lapack-netlib")

**Comment by insertinterestingnamehere** [comment]
Yah, those are the same routines I had to remove from the copied lists of sources to originally get this to work. Thanks for the input.

**Comment by insertinterestingnamehere** [comment]
It looks like we need additional changes from https://github.com/Reference-LAPACK/lapack/pull/118. It may be worth just upgrading to 3.7.1 to get the relevant bugfixes. Thoughts?

**Comment by ghost** [comment]
If you're up for it, then I don't see why not. It only depends on how much work you are willing to do.

**Comment by insertinterestingnamehere** [comment]
That seems like the easier way out of the current rabbit hole. It's better to just update than to keep picking out additional patches. I'm pretty much out of time to work on this today though, so it'll probably take another day or two.

**Comment by ghost** [comment]
That's fine with me.

**Comment by martin-frbg** [comment]
My suggestion is to crawl out of the rabbit hole back to the working code you had about four hours ago, and leave fixing the unrelated, pre-existing issues with missing functions to another PR. (I had optimistically claimed to provide the PR bringing 3.7.1 to OpenBLAS "in a week or so" in mid august, #1273 but things went downhill from there for me)

**Comment by insertinterestingnamehere** [comment]
Yah, tracking down these additional missing routine issues is getting pretty far afield from the original purpose of this PR. I've moved the two newest commits to https://github.com/insertinterestingnamehere/OpenBLAS/tree/lapack_update and rolled this branch back to not include them. Work can continue there as time permits. FWIW I tried dropping the LAPACK 3.7.1 source in as is and the CMake build with flang actually worked, but the update brought in or exposed new bugs in the existing makefiles.

**Comment by martin-frbg** [comment]
Yeah there are some changed makefile targets in 3.7.1 and the introduction of a LAPACKE_WITH_TMG define as noted in #1273. (Possibly makes sense to update to netlib git rather than 3.7.1 even...)

**Comment by martin-frbg** [comment]
FYI netlib appears to be preparing a 3.8.0 release right now.

**Comment by martin-frbg** [comment]
I put the 3.8.0 update into PR #1366 (Not that I wanted to make your work obsolete, it just seemed easier to me to do it that way rather than build on your branch. Still ended up with a push-pull game worthy of Alice in Wonderland)

**Comment by insertinterestingnamehere** [comment]
Awesome. I'll try that branch out. Thanks for taking care of that. I wasn't meaningfully further than the work already shown here, and even that was basically just backporting a few patches to 3.7.0.

**Pull request merged**
