### PR TITLE
Fix LAPACK unit testing build issues.

### PR DESCRIPTION
**Pull request by ChipKerchner**
Fix LAPACK unit testing build issues for AIX.

### CODE REVIEW

**Comment by martin-frbg** [comment]
I wonder what kind of build failures you are seeing with more than 32 threads - is it parts of LAPACK missing due to missed dependencies like in #4514 or something else ?

**Comment by ChipKerchner** [comment]
```
/opt/IBM/openxlC/17.1.2/bin/ibm-clang_r -c -O2 -DSMALL_MATRIX_OPT -DMAX_STACK_ALLOC=2048 -fopenmp -DHAVE_P10_SUPPORT -Wall -DF_INTERFACE
_IBM -fPIC -DDYNAMIC_ARCH -DSMP_SERVER -DUSE_OPENMP -DNO_WARMUP -DMAX_CPU_NUMBER=320 -DMAX_PARALLEL_NUMBER=1 -DBUILD_BFLOAT16 -DBUILD_SI
NGLE=1 -DBUILD_DOUBLE=1 -DBUILD_COMPLEX=1 -DBUILD_COMPLEX16=1 -DVERSION=\"0.3.26.dev\" -Ofast -mcpu=power10 -mtune=power10 -mvsx -fno-fa
st-math -DUSE_OPENMP -fopenmp -fno-integrated-as -m64 -UASMNAME -UASMFNAME -UNAME -UCNAME -UCHAR_NAME -UCHAR_CNAME -DASMNAME=sspmv -DASM
FNAME=sspmv_ -DNAME=sspmv_ -DCNAME=sspmv -DCHAR_NAME=\"sspmv_\" -DCHAR_CNAME=\"sspmv\" -DNO_AFFINITY -I.. -I. -UDOUBLE  -UCOMPLEX spmv.c
 -o sspmv.o
make[1]: *** [Makefile:1111: sspmv.o] Error 127
make[1]: *** Waiting for unfinished jobs....
.ibm-clang: error: unable to execute command: posix_spawn failed: Resource temporarily unavailable
make[1]: *** [Makefile:1717: cblas_srotmg.o] Error 1
.ibm-clang: error: unable to execute command: posix_spawn failed: Resource temporarily unavailable
.ibm-clang: error: unable to execute command: posix_spawn failed: Resource temporarily unavailable
```

**Comment by ChipKerchner** [comment]
I don't think using all the cores for a build is necessarily a good thing.

**Comment by martin-frbg** [comment]
Oh, ok - that looks like a locally imposed limit on the number of concurrent threads. Not sure if this should be enforced by the build system though, when local conventions will be variable and MAKE_NB_JOBS is already documented

**Comment by ChipKerchner** [comment]
@martin-frbg Can you point to the documentation about MAKE_NB_JOBS?

**Comment by martin-frbg** [comment]
Makefile.rule is currently what goes for documentation of build options, but that is set to change soon, thanks to work mentioned in #4166

**Comment by ChipKerchner** [comment]
Please include this for 0.3.27

**Pull request merged**
