### PR TITLE
Add cpu detection support for Zhaoxin processors

### LINKED ISSUE #3295: Add cpu detection support for Zhaoxin processors
The current openblas version cannot recognize the Zhaoxin CPU. Now add cpu detection support for Zhaoxin processors. Set the default TARGET to NEHALEM.

### PR DESCRIPTION
**Pull request by jonaszhou1**
Fix #3295

Signed-off-by: JonasZhou <JonasZhou@zhaoxin.com>

### CODE REVIEW

**Comment by martin-frbg** [comment]
Thank you, that is certainly a bit cleaner than my guesses. I wonder if there is AVX/AVX2 support in newer models (which would allow identifying them as Sandybridge/Haswell for somewhat faster code) ?

**Comment by jonaszhou1** [comment]
> 
> 
> Thank you, that is certainly a bit cleaner than my guesses. I wonder if there is AVX/AVX2 support in newer models (which would allow identifying them as Sandybridge/Haswell for somewhat faster code) ?

Family 7 processors support AVX, but it performance is weak.

**Comment by jonaszhou1** [comment]
> 
> 
> Thank you, that is certainly a bit cleaner than my guesses. I wonder if there is AVX/AVX2 support in newer models (which would allow identifying them as Sandybridge/Haswell for somewhat faster code) ?

Support AVX, and AVX2 is partially supported, but SSE instructions perform better on some platforms.

**Comment by martin-frbg** [comment]
I see, thanks.

**Pull request merged**
