### PR TITLE
Support CORTEXA55 0xd05 and reduce drone resource usage

### PR DESCRIPTION
**Pull request by brada4**
And let clang++ compile if needed.

### CODE REVIEW

**Comment by brada4** [comment]
Ill make separate if this gets through, at least default was to much for 128GB swap on raspberry

**Comment by martin-frbg** [comment]
Pretty sure there is something else going on at drone.io - they are using serious hardware and there is no way addition of just one more DYNAMIC_ARCH target could have driven up build times like that. Perhaps it is just rate limiting kicking in due to the number of rebuilds in fairly quick succession.

**Comment by brada4** [comment]
Ill wait some before re-opening A55

**Comment by martin-frbg** [comment]
Looks like closing the PR does not (always) cancel the associated CI on drone (which I am pretty sure it did in the past).

**Comment by brada4** [comment]
Does not let me operate cancel button either ;-)

**Comment by martin-frbg** [comment]
Interesting. I managed to cancel your pending re-run of this PR, and its original invocation finished successfully a minute ago. I think there are no pending jobs now.

**Comment by brada4** [comment]
I will push both, if it fails I will follow the slow way one a day.

**Comment by brada4** [comment]
Looks like cached result is stuck.

**Comment by brada4** [comment]
Rationale of having it in the low-end pool:
- mass market pieces will be always cache-challenged
- it is power-efficient piece, unlikely to scale into upper segments.
I suppose it needs a rewrite around cpuid (and dynamic thereof) to be in best shape for mass market SoC products and enormous network switches alike.

**Pull request closed without merging**
