### PR TITLE
Fix unwanted "hard" fallback to Prescott in runtime detection of Intel cpus 

### LINKED ISSUE #4267: detected architecture is Prescott on a recent CPU
This causes the scikit-learn error [#27613](https://github.com/scikit-learn/scikit-learn/issues/27613)

```
python -m threadpoolctl -i scipy

[
  {
    "user_api": "blas",
    "internal_api": "openblas",
    "num_threads": 4,
    "prefix": "libopenblas",
    "filepath": "/home/jerome/miniconda3/envs/3.11/lib/libopenblasp-r0.3.24.so",
    "version": "0.3.24",
    "threading_layer": "pthreads",
    "architecture": "Prescott"
  }
]
```

`lscpu`
<details>
<pre>
Architecture:                       x86_64
CPU op-mode(s):                     32-bit, 64-bit
Address sizes:                      46 bits physical, 48 bits virtual
Byte Order:                         Little Endian
CPU(s):                             20
On-line CPU(s) list:                0-19
Vendor ID:                          GenuineIntel
Model name:                         13th Gen Intel(R) Core(TM) i7-1370P
CPU family:                         6
Model:                              186
Thread(s) per core:                 2
Core(s) per socket:                 14
Socket(s):                          1
Stepping:                           2
CPU max MHz:                        5200.0000
CPU min MHz:                        400.0000
BogoMIPS:                           4377.60
Flags:                              fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf tsc_known_freq pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb ssbd ibrs ibpb stibp ibrs_enhanced tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid rdseed adx smap clflushopt clwb intel_pt sha_ni xsaveopt xsavec xgetbv1 xsaves avx_vnni dtherm ida arat pln pts hwp hwp_notify hwp_act_window hwp_epp hwp_pkg_req hfi umip pku ospke waitpkg gfni vaes vpclmulqdq tme rdpid movdiri movdir64b fsrm md_clear serialize pconfig arch_lbr ibt flush_l1d arch_capabilities
Virtualization:                     VT-x
L1d cache:                          544 KiB (14 instances)
L1i cache:                          704 KiB (14 instances)
L2 cache:                           11.5 MiB (8 instances)
L3 cache:                           24 MiB (1 instance)
NUMA node(s):                       1
NUMA node0 CPU(s):                  0-19
Vulnerability Gather data sampling: Not affected
Vulnerability Itlb multihit:        Not affected
Vulnerability L1tf:                 Not affected
Vulnerability Mds:                  Not affected
Vulnerability Meltdown:             Not affected
Vulnerability Mmio stale data:      Not affected
Vulnerability Retbleed:             Not affected
Vulnerability Spec store bypass:    Mitigation; Speculative Store Bypass disabled via prctl
Vulnerability Spectre v1:           Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:           Mitigation; Enhanced IBRS, IBPB conditional, RSB filling, PBRSB-eIBRS SW sequence
Vulnerability Srbds:                Not affected
Vulnerability Tsx async abort:      Not affected
</pre>
</details>

discussing with @ogrisel , we are wondering why the feature-based fallback strategy added in https://github.com/OpenMathLib/OpenBLAS/pull/3485 does not apply here

### PR DESCRIPTION
**Pull request by martin-frbg**
fixes #4267

### CODE REVIEW

**Comment by ogrisel** [comment]
@jeromedockes can you please rebuild this branch of OpenBLAS on your host with DYNAMIC_ARCH enabled and check that the right architecture is detected (e.g. with threadpoolctl)?

**Comment by jeromedockes** [comment]
@ogrisel  sorry for the delay. yes I confirm that the right architecture is detected now. I compiled this

```c
#include <cblas.h>
#include <stdio.h>

void main() { printf("architecture: %s\n", openblas_get_corename()); }
```

with the develop branch of OpenBLAS (before this PR was merged) I get
```
architecture: Prescott
```

and with this branch I get

```
architecture: Haswell
```

(and in any case if I compile OpenBLAS without DYNAMIC_ARCH enabled I get `architecture: HASWELL`

**Comment by ogrisel** [comment]
Thanks very much for the confirmation !

**Comment by ogrisel** [comment]
And thanks @martin-frbg for the quick fix.

**Pull request merged**
