### PR TITLE
Fix various source comment typos

### PR DESCRIPTION
**Pull request by luzpaz**
Found via `codespell -q 3 -L amin,als,ba,dum,mone,nd,nto,orign -S Changelog.txt,./lapack*`

### CODE REVIEW

**Comment by martin-frbg** [comment]
Thanks. I must admit I am of two minds when it comes to non-code fixes. On one hand, they tend to clutter up diffs and create a wrong impression that lots of things changed in the code. On the other, I once worked on code written by a brilliant engineer who was legasthenic so I understand that searching for a particular function based on likely code comments can be a huge pain.

**Comment by brada4** [comment]
reference/ is remnant of never implemented test framework. Actually there was a issue reported that never materialized to get rid of it. It is a copy of upstream NetLib BLAS, thus immutable here, down stream.
For the rest - even imperfect, all the misteaks are pretty much understandable even for basic engilsh speaker.

**Comment by luzpaz** [comment]
Close ticket then ?

**Comment by martin-frbg** [comment]
My intention is/was to review/merge this shortly before the next release (provided it has no conflicts). But as stated above it seems pretty pointless to spell-check dead code (reference/) or commented-out messages (init.c) and the remaining transposition typos are not that hard to read.

**Pull request closed without merging**
