### PR TITLE
AVX2 STRSM kernels

### PR DESCRIPTION
**Pull request by wjc404**
The performances of AVX2 STRSM on HSW-EP & SKX CPUs are comparable to MKL2019 now.

### CODE REVIEW

**Comment by wjc404** [comment]
Thanks for accepting my code. The kernels passed basic tests using the program in 
[strsm_kernel_tester.tar.gz](https://github.com/xianyi/OpenBLAS/files/4341438/strsm_kernel_tester.tar.gz)

**Comment by martin-frbg** [comment]
This _appears_ to have caused a segfault in the scipy testsuite unfortunately https://github.com/conda-forge/scipy-feedstock/pull/130 although it passed all the usual BLAS and LAPACK tests

**Comment by isuruf** [comment]
A simpler reproduction

> $ python
Python 3.7.6 | packaged by conda-forge | (default, Jun  1 2020, 18:57:50) 
[GCC 7.5.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy as np
>>> t = np.array([[1, 0.5], [-1, 0.5]])
>>> matrix_a = np.dot([(1,2) for i in range(1000000)], t)

**Comment by bgruening** [comment]
Can we revert this PR until it is fixed?

**Comment by martin-frbg** [comment]
Not reproduced with the simple reproducer so far (but using python 3.6.10 rather than 3.7 - is that expected to make a difference ?)

**Comment by bgruening** [comment]
@martin-frbg which architecture are you using. We have collected a few more informations here: https://github.com/conda-forge/openblas-feedstock/issues/101

Its also reproducible on travis for me.

**Comment by martin-frbg** [comment]
SKX with OpenBLAS built for Haswell, and Kaby Lake (but using a Virtualbox VM) so far. (Valgrind on the latter also unhelpful, lots of screaming about python and numpy but no backtrace leading into OpenBLAS). Would love to see the source line in the assembly where it crashes to get some kind of handle on this problem.

**Comment by martin-frbg** [comment]
Still cannot reproduce this on i7-8700K either :-(
Does your default conda build use any other compilation options in addition to what was mentioned in https://github.com/conda-forge/openblas-feedstock/issues/101 ?

**Comment by martin-frbg** [comment]
Just saw one crash now, but only with a DYNAMIC_ARCH build and the valgrind log started with a free of an unallocated region by/in the python parser. This was then followed by a segfault caused by "bad permissions for mapped region" in the DGEMM ONCOPY kernel. (Which would suggest it has nothing to do with this particular PR)

**Comment by martin-frbg** [comment]
Created issue #2728 to track the numpy/scipy segfaults as this PR is most likely unrelated

**Comment by bgruening** [comment]
Thanks for checking this! If you have anything I can test please let me know. If we run the same code with openblas 0.3.9 it works for us. Thats why we thought its an openblas issue.

**Pull request merged**
