### PR TITLE
Add new targets for ARM64

### PR DESCRIPTION
**Pull request by ashwinyes**

### CODE REVIEW

**Comment by martin-frbg** [comment]
Seems the travis check failed only because the vm could not fetch compiler packages from ubuntu.com

**Comment by ashwinyes** [comment]
May I know what all is tested in the travis check?

**Comment by xianyi** [comment]
@ashwinyes ，It doesn't test ARM target on Travic-CI.

**Comment by ashwinyes** [comment]
Ok. Thanks. In that case these should not cause any failures.

Moreover it is adding new targets for ARM64. So it should not affect any existing ARM64 targets

**Comment by ashwinyes** [comment]
Reopened the pull request to trigger the travis checks again.

**Comment by ashwinyes** [comment]
@xianyi The Travis checks have completely successfully. Request you to merge if the changes looks  OK.

**Pull request merged**
