### PR TITLE
Honor cgroup/cpuset limits when enumerating cpus

### PR DESCRIPTION
**Pull request by martin-frbg**
Fix for #1155

### CODE REVIEW

**Comment by xianyi** [comment]
@jirutka , We will revert this PR, then release a new version.

**Comment by jirutka** [comment]
I don't think it's needed to revert entire PR or commit, just fix ifdefs in memory.c.

**Comment by jirutka** [comment]
I don't think it's needed to revert entire PR or commit, just fix ifdefs in memory.c.

**Comment by martin-frbg** [comment]
I have reverted the commit as I cannot fix it immediately. From #630 it could be that init.c also needs changing. Will try try to set up a test environment locally before redoing the PR...

**Pull request merged**
