### PR TITLE
Support force TARGET=VORTEX

### PR DESCRIPTION
**Pull request by isuruf**

### CODE REVIEW

**Comment by isuruf** [comment]
I'm not sure what the defines should be. I made a guess.

**Comment by martin-frbg** [comment]
Thanks. I'll reduce my PR accordingly. (BTW the cache size information is unused except on a few historic targets, so wrong guesses should not hurt)

**Comment by isuruf** [comment]
Thanks. I'll close this PR then. the only diff worth salvaging is the `L2_DATA_SIZE->L2_SIZE` change in `cpuid_arm64.c`

**Comment by martin-frbg** [comment]
Picked up now, thank you.

**Pull request closed without merging**
