### PR TITLE
[OpenBlas]:Add benchmark tpmv.c and modify benchmark/Makefile

### PR DESCRIPTION
**Pull request by aaawuanjun**
[Description]:Solve the problem of missing tpmv.c benchmark file

### CODE REVIEW

**Comment by aaawuanjun** [comment]
The building error of power8, can not find command gfortran.
maybe the Ci environment lack of gfortran command？

image

**Comment by martin-frbg** [comment]
Yes, this does look like an error on the Travis side - I think their powerpc setup is still a bit experimental. gfortran was certainly there yesterday.

**Comment by aaawuanjun** [comment]
Is the pow8 ci env ok now? 
is someone change gfortran or remove the gfortran of the power 8 , has anyone can reinstall gfortran to make sure the basic env has no problem.

**Comment by martin-frbg** [comment]
Did not manage to get gfortran back on ppc64 so far, so changed the makefiles to keep them from trying to run the tests when fortran is not available.

**Pull request merged**
