### PR TITLE
Add macOS to the Travis testing matrix

### PR DESCRIPTION
**Pull request by ararslan**
Let's see what happens...

### CODE REVIEW

**Comment by martin-frbg** [comment]
"Could not parse .travis.yml" unfortunately...

**Comment by martin-frbg** [comment]
I _think_ I got it working now, simply by moving the osx build to the top of the include list.

**Comment by ararslan** [comment]
> "Could not parse .travis.yml" unfortunately...

Ah yes, I had meant to validate the YAML using Travis' tool before pushing. Probably why the Travis webhook didn't show up at all.

> I think I got it working now

Where were you able to do that? I don't see macOS in the Travis config, since the commit here was reverted without replacement.

I think I know what the issue was, I can try again in another PR.

**Comment by ararslan** [comment]
See #1512

**Comment by martin-frbg** [comment]
I have experimented with travis in my fork, after adding the travis connection to it. (Which I assume you did in your fork now as well ?)

**Pull request merged**
