### PR TITLE
Fix MinGW/Clang 64 bits detection.

### PR DESCRIPTION
**Pull request by MehdiChinoune**
CMAKE_COMPILER_IS_GNUCC is only valid for GCC.

### CODE REVIEW

**Comment by MehdiChinoune** [comment]
Travis-CI failue on PPC64LE is not related to my changes

**Comment by martin-frbg** [comment]
Thanks - the mingw/clang combination has not come up before. (I wonder if your change would exclude non-mingw builds of gcc - assuming they exist?)

**Comment by martin-frbg** [comment]
> Travis-CI has PPC64LE is not related to my changes

Right - looks like a broken network link. And now Travis tells me we have run out of credits again - despite using only third-party hardware for which they claim not to charge anything at all.

**Comment by MehdiChinoune** [comment]
> Thanks - the mingw/clang combination has not come up before. (I wonder if your change would exclude non-mingw builds of gcc - assuming they exist?)

The conditions/tests were made to set MINGW64.

**Comment by martin-frbg** [comment]
I was just wondering if the original code would happen to support more than just mingw, but I guess any others would probably be taken care of by the CMAKE_CL_64 later on. Thanks again for the patch.

**Pull request merged**
