### PR TITLE
macOS PowerPC: fix CMake build

### LINKED ISSUE #4366: Configure broken on PowerPC with CMake: `string sub-command REGEX, mode MATCHALL needs at least 5 arguments total to command`
Both PPC970 and PPCG4 fail likewise. Notice, that currently arch detection is broken in the master for PowerPC 32-bit, when building with CMake, so configure gonna fail earlier. But that bug I fixed, with this one I am not sure what to do:

```
-- Reading vars from /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_math_OpenBLAS/OpenBLAS-devel/work/OpenBLAS-864c65b526945604597ef9da1571a2f36b408054/kernel/power/KERNEL...
-- Reading vars from /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_math_OpenBLAS/OpenBLAS-devel/work/OpenBLAS-864c65b526945604597ef9da1571a2f36b408054/kernel/power/KERNEL.PPCG4...
CMake Error at cmake/utils.cmake:106 (string):
  string sub-command REGEX, mode MATCHALL needs at least 5 arguments total to
  command.
Call Stack (most recent call first):
  kernel/CMakeLists.txt:13 (ParseMakefileVars)
  kernel/CMakeLists.txt:1371 (build_core)


CMake Error at cmake/utils.cmake:106 (string):
  string sub-command REGEX, mode MATCHALL needs at least 5 arguments total to
  command.
Call Stack (most recent call first):
  kernel/CMakeLists.txt:13 (ParseMakefileVars)
  kernel/CMakeLists.txt:1371 (build_core)
```

Also see: https://trac.macports.org/ticket/68868

@martin-frbg Could you take a look, please?

### PR DESCRIPTION
**Pull request by barracuda156**
Fixes: https://github.com/OpenMathLib/OpenBLAS/issues/4366

@martin-frbg So yes, configure failure was due to extra spaces.

UPD. And the second commit fixes linking.

### CODE REVIEW

**Comment by barracuda156** [comment]
@martin-frbg Thank you!

**Comment by martin-frbg** [comment]
Well, thank _you_ for doing all the debugging on a platform I cannot test.

**Comment by barracuda156** [comment]
Wonder if that CMake issue with spaces is by design or unintentional from its side.

**Comment by martin-frbg** [comment]
I haven't looked in detail yet, but it is probably a bit of sloppy coding (by me) in utils.cmake - but there must be a CMake version component to it as the problem was not reproducible on IBM POWER 8/9 running CentOS.

**Pull request merged**
