### PR TITLE
Add benchmark for SPMV and fix segmentation fault when data size >= 50000

### PR DESCRIPTION
**Pull request by xiaofengF**
Add benchmark for SPMV and fix segmentation fault when data size >= 50000

### CODE REVIEW

**Comment by martin-frbg** [comment]
I'm beginning to suspect that it is actually a long-standing error in our version of the LAPACK Makefile. xSPMV is overloaded with an OpenBLAS implementation from driver/level2 so the original fortran version from the reference implementation needs to be excluded from the build.

**Comment by xiaofengF** [comment]
> I'm beginning to suspect that it is actually a long-standing error in our version of the LAPACK Makefile. xSPMV is overloaded with an OpenBLAS implementation from driver/level2 so the original fortran version from the reference implementation needs to be excluded from the build.

But I can't understand why the fortran version doesn't affect others, but only the cspmv and zspmv.

**Comment by xiaofengF** [comment]
> I'm beginning to suspect that it is actually a long-standing error in our version of the LAPACK Makefile. xSPMV is overloaded with an OpenBLAS implementation from driver/level2 so the original fortran version from the reference implementation needs to be excluded from the build.

 Maybe you can first pull the benchmark addition for sspmv and dspmv, because openblas only have s/d spmv in the cblas.h. c/z spmv is not that important.

**Comment by martin-frbg** [comment]
Comparing with the reference implementation, it is indeed only SSPMV and DSPMV that are in BLAS (and consequently CBLAS), while CSPMV and ZSPMV are LAPACK auxiliaries that do not even have a LAPACKE interface for them. Probably some "historic" reason for this distinction...

**Pull request merged**
