### PR TITLE
Restore _Atomic define before stdatomic.h for old gcc

### PR DESCRIPTION
**Pull request by martin-frbg**
see #1593

### CODE REVIEW

**Comment by dzyong** [comment]
I haven't found `C_GCC` and `__GNU_C__`, where do you get that?
I only find `__GNUC__`, it's used like this:

`#if __GNUC__ > 7`

**Comment by martin-frbg** [comment]
C_GCC is defined by gcc I think - it is already used in several places in the file. `__GNU_C__` was just a misspelling in my issue comment (fixed now).

**Comment by dzyong** [comment]
I compile this code on ubuntu 16.04 with gcc:
```
#include <stdio.h>

void main(){
#ifdef C_GCC
    printf("C_GCC defined\n");
#else
    printf("C_GCC not defined\n");
#endif
}
```
It print `C_GCC not defined`.

**Comment by martin-frbg** [comment]
Ah, sorry. C_GCC is actually set by c_check (written to config.h)

**Pull request merged**
