### PR TITLE
Update cpuid_x86.c

### PR DESCRIPTION
**Pull request by martin-frbg**
Support Intel C27xx Avoton via Nehalem kernel ref #548

### CODE REVIEW

**Comment by xianyi** [comment]
@martin-frbg , thank you for the patch.

Please update `driver/others/dynamic.c` at same time.

**Comment by martin-frbg** [comment]
Done, sorry about the initial omission (and the noise level here, did not expect the pull request to update automatically).

**Comment by xianyi** [comment]
@martin-frbg , I rebase your patch into one patch. Add some lines at `get_coretype` function.

**Comment by martin-frbg** [comment]
Thx. I hope to remember to look here to remind myself how it is done if I ever do this again.

**Pull request closed without merging**
