### PR TITLE
Add minimum threshold for number of buffers

### PR DESCRIPTION
**Pull request by brada4**
And dont break expectation that single-thread version can work in many threads.
#1847

### CODE REVIEW

**Comment by martin-frbg** [comment]
Also related are #938, #1141 - though it could be that is it ultimately the GEMM buffer handling that needs looking into.

**Comment by brada4** [comment]
Yes, it is wiping dirt under doormat type of solution.

**Comment by martin-frbg** [comment]
Not sure if we want to go all the way to 64 as at least with the non-tls implementation this will actually have an impact on memory requirements ?

**Comment by brada4** [comment]
Just in memory.c
```
#endif /* defined(SMP) */
    local_memory_table = (struct alloc_t **)malloc(sizeof(struct alloc_t *) * NUM_BUFFERS);
    memset(local_memory_table, 0, sizeof(struct alloc_t *) * NUM_BUFFERS);
#if defined(SMP)
```
i.e more 62 64-bit pointers (496 bytes) get pre-allocated for 1-CPU version

**Comment by martin-frbg** [comment]
Yes, but that's the experimental TLS version you are looking at - pretty sure that in the other/older/default implementation it corresponds to an actual allocation.

**Comment by brada4** [comment]
The "old" version
(8+8+8+8+48)*62=4960
```
static volatile struct {
  BLASULONG lock;
  void *addr;
#if defined(WHEREAMI) && !defined(USE_OPENMP)
  int   pos;
#endif
  int used;
#ifndef __64BIT__
  char dummy[48];
#else
  char dummy[40];
#endif
```

**Comment by martin-frbg** [comment]
Just looking for reasons why nobody tried to uncouple NUM_BUFFERS from NUM_CPU (NUM_THREADS) before, although this problem has come up in some form or other every few months in the past years.

**Comment by brada4** [comment]
I think it is buffer (me) or two (formula there) per thread, the big issue is that single-threaded version depends on this structure at all.

**Pull request merged**
