### PR TITLE
[WIP] Use arm neon instructions to optimize gemm beta operation

### PR DESCRIPTION
**Pull request by Zeyiii**
This optimization can improve performance of  gemm_beta operation nearly twice. PTAL.

### CODE REVIEW

**Review by brada4 — CHANGES_REQUESTED** [review]
Guide says NEON is optional, so generic kernel should not assume it as default. It is present in all other real cores though

**Comment by martin-frbg** [comment]
I believe the DGEMM_BETA could/should be declared in KERNEL.ARMV8 rather than the generic KERNEL. (IIRC neon extensions are already used in at least some of the optimized arm64 kernels)

**Comment by Zeyiii** [comment]
> I believe the DGEMM_BETA could/should be declared in KERNEL.ARMV8 rather than the generic KERNEL. (IIRC neon extensions are already used in at least some of the optimized arm64 kernels)

You're right. I have corrected it.

**Comment by martin-frbg** [comment]
Thanks

**Pull request merged**
