### PR TITLE
Fix build issues when path contains whitespace

### PR DESCRIPTION
**Pull request by alexkaratarakis**
Users have submitted fixes in [vcpkg](https://github.com/Microsoft/vcpkg) for building openblas in paths-with-whitespace.
This PR contains the fixes; they are simple quotes in CMake around variables that represent paths. 

Related:
- https://github.com/Microsoft/vcpkg/tree/master/ports/openblas
- https://github.com/Microsoft/vcpkg/pull/1749

### CODE REVIEW

**Comment by martin-frbg** [comment]
Travis error appears to be unrelated (timeout), but this needs to be merged after the big cmake PR#1279

**Comment by martin-frbg** [comment]
Closing to trigger a rebuild (by reopening)

**Comment by martin-frbg** [comment]
Could not shake that hung appveyor job loose that blocked the merge, so I included your changes in my PR #1323

**Comment by alexkaratarakis** [comment]
Sweet, thanks!

**Pull request closed without merging**
