### PR TITLE
Use BLAS rather than CBLAS in test_fork.c

### PR DESCRIPTION
**Pull request by oon3m0oo**
This is handy for people not lapack.

### CODE REVIEW

**Comment by sandwichmaker** [comment]
err @oon3m0oo meant people not building the cblas API.

**Comment by martin-frbg** [comment]
Rerun the tests once 1625 is in, I suspect right now people not fork...

**Comment by oon3m0oo** [comment]
It's still useful and caught a real bug that would have occurred if people do fork.  I've been running my testing with #1625 applied, but no hurry.

**Comment by martin-frbg** [comment]
My point is just that CI for this PR will be using the state of the develop branch without 1625 applied, which is likely the reason for the fork utest failing on some platforms

**Comment by martin-frbg** [comment]
Fails all the iNTERFACE64=1 tests it seems (the xcode one passes, but is not configured to run utest at all). Probably needs to be `BLASINT n` now rather than `int n` ?

**Comment by oon3m0oo** [comment]
Ahh yep, you're probably right.

**Comment by martin-frbg** [comment]
Travis seems to think otherwise, but has been acting up a bit lately.

**Comment by martin-frbg** [comment]
It would probably make sense to remove the `not (NO_CBLAS)` restriction from the utest Makefile and CMakeLists.txt with the same PR ?

**Comment by oon3m0oo** [comment]
Yep, done.

**Pull request merged**
