### PR TITLE
Rectify _?matcopy size calculation

### PR DESCRIPTION
**Pull request by brada4**
Shall address #3160 , avoiding oldest bit mis-handled as the sign.

### CODE REVIEW

**Review by martin-frbg — CHANGES_REQUESTED** [review]
Hmm.. I do not like the unrelated&unannounced change to the allocation here - have to admit wernsaar's code looks a bit unexpected but I guess technically the output matrix is allowed to be bigger than the input (with some elements undefined)

**Comment by brada4** [comment]
codeql demo says multiplication result is signed then assigned to unsigned eventually losing sign bit via overflow that might have been there. It is just arithmetic problem, sad it happens in the face of malloc.
this is just to clear the warning, quite obvious some sanity checking would be handy, but then we have no way to give controlled feedback

**Comment by martin-frbg** [comment]
> this is just to clear the warning,

my point is that you removed the `if *lda > *ldb` logic for the calculation of msize. I am still not entirely sure if it is really needed, but it looks too elaborate to be a random mistake - and it has nothing to do with the intermediate overflow that you set out to fix. 
(probably it would even be enough to put parentheses around the `ldb * sizeof` part so that everything gets cast to size_t automatically)

**Comment by brada4** [comment]
OK, can do double way if that is f concern.

**Comment by brada4** [comment]
Thanks, fixed with other PR

**Pull request closed without merging**
