### PR TITLE
Implementaion of dasum, sasum with AVX2 & AVX512 intrinsic

### PR DESCRIPTION
**Pull request by xiegengxin**
Implement dasum, sasum with AVX2 & AVX512 intrinsic for x86_64 architecture to improve the performance.

### CODE REVIEW

**Comment by brada4** [comment]
I think you need to force-align presumed jump targets to palign(5) or so , but measure.
What about AMD ZEN and Intel COOPERLAKE ?

**Comment by brada4** [comment]
AVX2 and AVX512 needs some warmup, otherwise for small samples it is hundreds of cycles unproductive

**Comment by xiegengxin** [comment]
1. Align to 64 byte or 32 byte.
2. When input array size is small (less than 256), using SSE intrinsic to instead of AVX512/AVX2. The performance won't worse too much.

| input size | Optimizaion vs Before |
|---|---|
|16|0.96x|
|32|1.03x|
|64|1.01x|
|128|0.99x|
|256|0.99x|
|512|0.95x|
|1024|1.16x|
|2048|1.18x|

**Comment by brada4** [comment]
From excellent resource at agner.org
> The first YMM or ZMM instruction takes 150-250 clock cycles -probably to start a power-up process

How does it work with intentionally unaligned input, and not ending so round?

**Pull request merged**
