### PR TITLE
Fix SCAL on x86 and RISCV_GENERIC

### PR DESCRIPTION
**Pull request by martin-frbg**
fixes two oversights from #4807

### CODE REVIEW

**Comment by mattip** [comment]
That was quick, thanks!

**Comment by mattip** [comment]
Dunno if you want to fix it, there are some errors with Windows_cl [starting here](https://dev.azure.com/martinkroeker/martinkroeker/_build/results?buildId=1181&view=logs&j=2d8ea0da-d599-5234-e06f-743200a8aa8e&t=30994467-7236-5890-7de5-bc1a1b096700&l=9907)
```
utest\test_gemv.c(22,15): error C2057: expected constant expression
```

I think that is coming from declarations like this https://github.com/OpenMathLib/OpenBLAS/blob/fb7c53c5e56469d95bcf13345bc3532381873fb6/utest/test_gemv.c#L21-L23

where N is not a constant expression.

**Comment by mattip** [comment]
Maybe you could `#define N` instead

**Comment by martin-frbg** [comment]
thanks for the pointer - I had seen the failure but did not find the actual error when wading through the Azure log, so was hoping it would be the same C99 thing that broke the manylinux build. indeed these should be defines (but at least that wasn't my fault except for not noticing in review)

**Pull request merged**
