### PR TITLE
Add trivial smoketest for xpotrf

### PR DESCRIPTION
**Pull request by pv**
Add a trivial test for the *potrf routines to utest.

We've now been burned a few times by "bad" openblas builds (on some platforms only) that had broken cholesky factorizations. It would be useful to catch those already when building openblas itself, so here is a PR that adds a trivial smoketest that should catch those.

### CODE REVIEW

**Comment by matthew-brett** [comment]
Guys - would you mind testing this patch on Windows 32-bit?  That is where we are seeing the numpy failure.

**Comment by pv** [comment]
The problematic case does not require just windows 32-bit, but also the specific compiler and maybe compiler flag choice, which I'm not sure is useful for openblas devs to spend time on. I tested myself that this test case correctly fails when using the "bad" build binaries, and it passes for correctly working potrf routines (as indicated by appveyor&travis).

**Comment by matthew-brett** [comment]
At the moment, though, the only situation we know this fails, is on Windows 32-bit, with the given compiler / flags and so on; so if this test passes with a standard mingw build, on Windows 32-bit, then we (numpyers) can try and track down which of our tweaks is causing the problem.

**Comment by pv** [comment]
@matthew-brett: the "standard" mingw-w64/32bit compiler shipped on appveyor produces problem-free binaries (indeed, remember that we already had this discussion vs. scipy). If necessary, let's discuss that elsewhere since it's probably not so relevant for openblas development.

Anyway, even if the failing compiler setup is rare, it would still be useful if the standard openblas test suite would have at least minimal testing of the potrf routines.

**Comment by matthew-brett** [comment]
Ah - no - sorry - I had not registered that https://github.com/xianyi/OpenBLAS/issues/1270 was the same issue.

**Comment by martin-frbg** [comment]
I'm all for detecting errors early, thanks :-)

**Pull request merged**
