### PR TITLE
Accomodate AIX install, which has different syntax

### PR DESCRIPTION
**Pull request by martin-frbg**
for #1803

### CODE REVIEW

**Comment by Teej42** [comment]
Okay, it is not recognizing the $OSNAME, so I will have to research what the solution should be.  Will update when I figure it out.

**Comment by martin-frbg** [comment]
Probably just a misplaced parenthesis in my commit - should be "($(OSNAME),AIX)" not "(($OSNAME),AIX)" sorry...

**Comment by Teej42** [comment]
Any advice on why these files are not "found"?  It is there:

$ sudo make install
make -j 2 -f Makefile.install install
make[1]: Entering directory '/medstat/advantage/scratch/focal_point/download/OpenBLAS'
Generating openblas_config.h in /opt/OpenBLAS/include
Generating f77blas.h in /opt/OpenBLAS/include
Generating cblas.h in /opt/OpenBLAS/include
Copying LAPACKE header files to /opt/OpenBLAS/include
find: bad status-- /opt/OpenBLAS/include/lapacke.h
install: File lapacke.h was not found.
make[1]: [Makefile.install:46: install] Error 2 (ignored)
find: bad status-- /opt/OpenBLAS/include/lapacke_config.h
install: File lapacke_config.h was not found.
make[1]: [Makefile.install:47: install] Error 2 (ignored)
find: bad status-- /opt/OpenBLAS/include/lapacke_mangling.h
install: File lapacke_mangling_with_flags.h.in was not found.
make[1]: [Makefile.install:48: install] Error 2 (ignored)
find: bad status-- /opt/OpenBLAS/include/lapacke_utils.h
install: File lapacke_utils.h was not found.
make[1]: [Makefile.install:49: install] Error 2 (ignored)
Copying the static library to /opt/OpenBLAS/lib
install: File libopenblas_power5p-r0.3.3.a was not found.
make[1]: *** [Makefile.install:51: install] Error 2
make[1]: Leaving directory '/medstat/advantage/scratch/focal_point/download/OpenBLAS'
make: *** [Makefile:336: install] Error 2

Here's the file status:

$ find . -name lapacke.h
./lapack-netlib/LAPACKE/include/lapacke.h
$ find . -name lapacke_config.h
./lapack-netlib/LAPACKE/include/lapacke_config.h
$ find . -name lapacke_mangling.h
./lapack-netlib/LAPACKE/include/lapacke_mangling.h
$ find . -name lapacke_utils.h
./lapack-netlib/LAPACKE/include/lapacke_utils.h
$ find . -name libopenblas_power5p-r0.3.3.a
./libopenblas_power5p-r0.3.3.a
$ find . -name lapacke_mangling_with_flags.h.in
./lapack-netlib/LAPACKE/include/lapacke_mangling_with_flags.h.in

**Comment by martin-frbg** [comment]
The only somewhat sane search result that I found (from comp.unix.aix ca. 10 years ago) suggests that the AIX install expects the destination argument to be the target directory rather than the full name of the target file. (So no on-the-fly renaming with this tool it seems.) Perhaps we should change this again to use the installbsd variant (is this available by default on AIX ?)

**Comment by Teej42** [comment]
I will have to ask around, but it's there for me:

$ installbsd
usage: install [-cs] [-g group] [-m mode] [-o owner] file1 file2;
        or file1 ... fileN directory

EDIT:  Just got confirmation, yes, by default it's there on all AIX servers.  Of course, there may be exceptions out there, but we should be able to depend on this file existing.

**Pull request merged**
