### PR TITLE
Add basic support for the Fujitsu A64FX

### LINKED ISSUE #2927: GEMM_... undeclared
I am using CentOS 8 on A64FX. On make I get lots of similar errors like 
- trsm.c:365:19: error: ‘GEMM_MULTITHREAD_THRESHOLD’ undeclared (first use in this function) 
- ../common_param.h:972:25: error: ‘GEMM_DEFAULT_OFFSET_B’ undeclared (first use in this function); did you mean ‘GEMM_DEFAULT_UNROLL_M’?

### PR DESCRIPTION
**Pull request by martin-frbg**
fixes #2927

### CODE REVIEW

**Comment by martin-frbg** [comment]
need to rebase getarch.c so that this does not dump SapphireRapids

**Comment by binebrank** [comment]
Hi there! Do you know if there is someone already working on implementing SVE dgemm kernels in assembly?
I have reasonable experience with Arm SVE (did some similar things for BLIS library) and would give this a try.

**Comment by martin-frbg** [comment]
Hi, I'm not aware of anyone already working on this (well, maybe xianyi is but I do not know...). You are certainly very welcome to contribute. I guess we are not aiming to compete with Fujitsu's own BLAS implementation just yet but a reasonably performant implementation might be useful all the same, if only for the convenience of projects that already rely on OpenBLAS on other platforms

**Comment by binebrank** [comment]
Thanks, I will keep you posted on my progress.

**Pull request merged**
