### PR TITLE
Initialize complex _dot result variable consistently at declaration time

### PR DESCRIPTION
**Pull request by brada4**
Fix one bug and wrap similar fragments to avoid confusing static checker that found it (`cppcheck-1.82-lp150.1.1.x86_64`)

@sharkcz should be minor change and for good?

### CODE REVIEW

**Comment by martin-frbg** [comment]
Not sure I see the bug here that this shuffling around of initializers is supposed to fix ?

**Comment by brada4** [comment]
You can apply via edit zarch only https://github.com/xianyi/OpenBLAS/pull/1877/commits/ae895f8648f7af07add892565edf847d1b988adf where they go uninitialized past the quick exit as only place initializing them.

**Comment by martin-frbg** [comment]
How so ? The assignment happens at the end of the function, and I do not see any open escape routes.

**Comment by brada4** [comment]
There is missing initalisation in the most likely route after that quick exit i.e one will start adding values to uninitialised memory acquired at declaration time.

**Comment by brada4** [comment]
Take it as a 2 step patch:
1/ add missing initialisation in the further path
2/ figure out it can actually be initialized at declaration
Others are just silencing checker, sort of does not matter much if it s one or two assignments per call initialising result.

**Comment by martin-frbg** [comment]
Sorry, I still do not see anything missing. Either the quick exit is taken after setting the result to zero, or the calculation uses the dot array and stores the result of the final addition in "result" before exiting.

**Comment by brada4** [comment]
Indeed

**Pull request closed without merging**
