### PR TITLE
[POWER] Vectorize SGEMV transpose reduce stage

### PR DESCRIPTION
**Pull request by ChipKerchner**
Vectorize SGEMV transpose (vector x matrix) reduce stage.

Decreases number of instructions in reduce by 5-6X.

### CODE REVIEW

**Comment by martin-frbg** [comment]
Unfortunately I am (belatedly) seeing test failures for SGEMV and SSYMV on POWER8 under CentOS Linux, ppc64le (host cfarm112 in the Gcc Compile Farm, which is said to be POWER8 8247-22L provided by OSUOSL) that can be fixed by reverting the changes to sgemv_t.c

**Comment by ChipKerchner** [comment]
I'm not 100% sure how to reproduce this failure.

**Comment by martin-frbg** [comment]
It was a surprise find from just running `make` on the aforementioned machine - however I notice now that it only has gcc8 installed. I'll try to reproduce this with a newer compiler if possible

**Comment by ChipKerchner** [comment]
Yes, I would recommend gcc11+ or later.

**Comment by ChipKerchner** [comment]
I could update this PR to only vectorize this data for P9.

**Comment by ChipKerchner** [comment]
Could update this PR (or a new one) to only vectorize this data for P9. Mainly it would be

#ifndef _ARCH_PWR9
old way
#else
new way
#endif

**Comment by martin-frbg** [comment]
I'm willing to leave it as it is now, if the error only appears with the ancient compiler. But the only other (gccfarm) little-endian power8 I have access to appears to be in Moscow of all places and its connection is flaky. So I'll have to see if building gcc14 on the old CentOS is faster than trying to git pull OpenBLAS _a la russe_

**Comment by martin-frbg** [comment]
Sorry, dropped the ball on this until being reminded by #5122 today - the failures on POWER8 turn out to be reproducible with gcc14 (also when building for TARGET=POWER8 on POWER10

**Pull request merged**
